images:
  adp-platform-manager:
    url: "{{ .Values.global.imageRegistry }}/tke-market/platform-manager:68_2606132006_stable_iaas_cos_a1507b69_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
