images:
  adp-platform-manager:
    url: "{{ .Values.global.imageRegistry }}/tke-market/platform-manager:101_2607281629_stable_iaas_v4.0.3.0_5d9cfa67_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
