images:
  adp-app-memory:
    url: "{{ .Values.global.imageRegistry }}/tke-market/app-memory:3_2607161449_stable_iaas_v4.0.3.0_cac00b6d_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
