images:
  adp-app-memory:
    url: "{{ .Values.global.imageRegistry }}/tke-market/bot-memory-server:5_2605071023_stable_v3.4.1.1_97a9d135_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
