apiVersion: v1
kind: Secret
metadata:
  name: cos-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  access-key-id: {{ .Values.seedServer.cosId | b64enc }}
  secret-access-key: {{ .Values.seedServer.cosKey | b64enc }}
