{{- if and .Values.minio.enabled (ne .Values.global.deployMode "leecher") (ne .Values.agent.trackerType "ntracker") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: minio-svc
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      affinity:
{{ toYaml .Values.affinity.seeder | indent 8 }}
      containers:
        - name: minio
          image: {{ .Values.images.minio.image }}:{{ .Values.images.minio.tag }}
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: cos-secret
                  key: access-key-id
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cos-secret
                  key: secret-access-key
          ports:
            - containerPort: 9000
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: minio
  ports:
    - port: 80
      targetPort: 9000
{{- end }}
