{
 "title": "HDFS DataNode",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datanode",
    "label": "DataNode",
    "query": "label_values(Hadoop_DataNode_HeartbeatsNumOps, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Live DataNodes",
   "type": "singlestat",
   "description": "Number of datanodes which are currently live",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(Hadoop_NameNode_NumLiveDataNodes{name=\"FSNamesystem\",pod=\"kdl-hadoop-hdfs-nn-0\"})"
    }
   ]
  },
  {
   "title": "Dead DataNodes",
   "type": "singlestat",
   "description": "Number of datanodes which are currently dead",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_NumDeadDataNodes{name=\"FSNamesystem\",pod=\"kdl-hadoop-hdfs-nn-0\"}"
    }
   ]
  },
  {
   "title": "Decom Live DataNodes",
   "type": "singlestat",
   "description": "Number of datanodes which have been decommissioned and are now live",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_NumDecomLiveDataNodes{name=\"FSNamesystem\",pod=\"kdl-hadoop-hdfs-nn-0\"}"
    }
   ]
  },
  {
   "title": "Decom Dead DataNodes",
   "type": "singlestat",
   "description": "Number of datanodes which have been decommissioned and are now dead",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_NumDecomDeadDataNodes{name=\"FSNamesystem\",pod=\"kdl-hadoop-hdfs-nn-0\"}"
    }
   ]
  },
  {
   "title": "Decommissioning Data Nodes",
   "type": "singlestat",
   "description": "Number of datanodes in decommissioning state",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_NumDecommissioningDataNodes{name=\"FSNamesystem\",pod=\"kdl-hadoop-hdfs-nn-0\"}"
    }
   ]
  },
  {
   "title": "Volume Failures Total",
   "type": "singlestat",
   "description": "Total number of volume failures across all Datanodes",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_VolumeFailuresTotal{name=\"FSNamesystem\",pod=\"kdl-hadoop-hdfs-nn-0\"}"
    }
   ]
  },
  {
   "title": "Estimated Capacity LostTotal",
   "type": "singlestat",
   "description": "An estimate of the total capacity lost due to volume failures",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_EstimatedCapacityLostTotal{name=\"FSNamesystem\",pod=\"kdl-hadoop-hdfs-nn-0\"}"
    }
   ]
  },
  {
   "title": "Stale DataNodes",
   "type": "singlestat",
   "description": "Current number of DataNodes marked stale due to delayed heartbeat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_StaleDataNodes{name=\"FSNamesystem\",pod=\"kdl-hadoop-hdfs-nn-0\"}"
    }
   ]
  },
  {
   "title": "Stale DataNodes",
   "type": "singlestat",
   "description": "Current number of DataNodes marked stale due to delayed heartbeat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_StaleDataNodes{name=\"FSNamesystem\",pod=\"kdl-hadoop-hdfs-nn-0\"}"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "singlestat",
   "description": "Total number of bytes written to DataNode",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_DataNode_BytesWritten{pod=~\"$datanode\"}"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "singlestat",
   "description": "Total number of bytes read from DataNode",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_DataNode_BytesRead{pod=~\"$datanode\"}"
    }
   ]
  },
  {
   "title": "Blocks Written",
   "type": "singlestat",
   "description": "Total number of blocks written to DataNode",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_DataNode_BlocksWritten{pod=~\"$datanode\"}"
    }
   ]
  },
  {
   "title": "Blocks Read",
   "type": "singlestat",
   "description": "Total number of blocks read from DataNode",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_DataNode_BlocksRead{pod=~\"$datanode\"}"
    }
   ]
  },
  {
   "title": "Blocks Replicated",
   "type": "singlestat",
   "description": "Total number of blocks replicated",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_DataNode_BlocksReplicated{pod=~\"$datanode\"}"
    }
   ]
  },
  {
   "title": "Blocks Removed",
   "type": "singlestat",
   "description": "Total number of blocks removed",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_DataNode_BlocksRemoved{pod=~\"$datanode\"}"
    }
   ]
  },
  {
   "title": "Blocks Verified",
   "type": "singlestat",
   "description": "Total number of blocks verified",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_DataNode_BlocksVerified{pod=~\"$datanode\"}"
    }
   ]
  },
  {
   "title": "Block Verification Failures",
   "type": "singlestat",
   "description": "Total number of verifications failures",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_DataNode_BlockVerificationFailures{pod=~\"$datanode\"}"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_DataNode_Threading_ThreadCount{pod=~\"$datanode\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{pod_name=~\"$datanode\"}[5m])*100) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"$datanode\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=\"$datanode\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod_name=~\"$datanode\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}-RSS"
    },
    {
     "expr": "sum(container_memory_cache{pod_name=~\"$datanode\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}-Cache"
    },
    {
     "expr": "sum(container_memory_swap{pod_name=\"$datanode\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}-Swap"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "Hadoop_DataNode_MemHeapUsedM{pod=~\"$datanode\"}",
     "legendFormat": "Current heap memory used"
    },
    {
     "expr": "Hadoop_DataNode_MemHeapCommittedM{pod=~\"$datanode\"}",
     "legendFormat": "Current heap memory committed"
    },
    {
     "expr": "Hadoop_DataNode_MemHeapMaxM{pod=~\"$datanode\"}",
     "legendFormat": "Max heap memory "
    }
   ]
  },
  {
   "title": "JVM Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "Hadoop_DataNode_MemNonHeapUsedM{pod=~\"$datanode\"}",
     "legendFormat": "Current non-heap memory used"
    },
    {
     "expr": "Hadoop_DataNode_MemNonHeapCommittedM{pod=~\"$datanode\"}",
     "legendFormat": "Current non-heap memory committed"
    },
    {
     "expr": "Hadoop_DataNode_MemNonHeapMaxM{pod=~\"$datanode\"}",
     "legendFormat": "Max non-heap memory "
    }
   ]
  },
  {
   "title": "IO Exception Num Ops / 30 min",
   "type": "graph",
   "description": "Number of IO Exception in 30 min.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Hadoop_DataNode_IOExceptionNumOps{pod=~\"$datanode\"}[30m])",
     "legendFormat": "IO Exception"
    }
   ]
  },
  {
   "title": "Data Send and Recive Bytes / 30 min",
   "type": "graph",
   "description": "Total number of sent bytes and received bytes in 30 min.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "delta(Hadoop_DataNode_SentBytes{pod=~\"$datanode\"}[30m])",
     "legendFormat": "Sent Bytes"
    },
    {
     "expr": "delta(Hadoop_DataNode_ReceivedBytes{pod=~\"$datanode\"}[30m])",
     "legendFormat": "Received Bytes"
    }
   ]
  },
  {
   "title": "Number of Sending Packets / 30 min",
   "type": "graph",
   "description": "Total number of sending packets in 30 min.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Hadoop_DataNode_SendDataPacketTransferNanosNumOps{pod=~\"$datanode\"}[30m])",
     "legendFormat": "Sent Data Packets"
    }
   ]
  },
  {
   "title": "Sending Packets Avg Time",
   "type": "graph",
   "description": "Average transfer time of sending packets in nanoseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "Hadoop_DataNode_SendDataPacketTransferNanosAvgTime{pod=~\"$datanode\"}",
     "legendFormat": "Sending Packets Avg Transfer  Time"
    },
    {
     "expr": "Hadoop_DataNode_SendDataPacketBlockedOnNetworkNanosAvgTime{pod=~\"$datanode\"}",
     "legendFormat": "Sending Packets Avg Waiting  Time"
    }
   ]
  },
  {
   "title": "Number of Flushes / 30 min",
   "type": "graph",
   "description": "Total number of flushes in 30 min.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Hadoop_DataNode_FlushNanosNumOps{pod=~\"$datanode\"}[30m])",
     "legendFormat": "Number of Flushes"
    }
   ]
  },
  {
   "title": "Flush Avg Time",
   "type": "graph",
   "description": "Average flush time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "Hadoop_DataNode_FlushNanosAvgTime{pod=~\"$datanode\"}",
     "legendFormat": "Average Flush Time"
    }
   ]
  },
  {
   "title": "Number of Fsync / 30 min",
   "type": "graph",
   "description": "Total number of fsync in 30 min.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Hadoop_DataNode_FsyncNanosNumOps{pod=~\"$datanode\"}[30m])",
     "legendFormat": "Number of Fsync"
    }
   ]
  },
  {
   "title": "Fsync Avg Time",
   "type": "graph",
   "description": "Average fsync time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "Hadoop_DataNode_FsyncNanosAvgTime{pod=~\"$datanode\"}",
     "legendFormat": "Average fsync time"
    }
   ]
  },
  {
   "title": "Number of Write Blocks / 30 min",
   "type": "graph",
   "description": "Total number of write operations in 30 min.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Hadoop_DataNode_WriteBlockOpNumOps{pod=~\"$datanode\"}[30m])",
     "legendFormat": "Number of Write Blocks"
    }
   ]
  },
  {
   "title": "Write Block Avg Time",
   "type": "graph",
   "description": "Average Write block time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "Hadoop_DataNode_WriteBlockOpAvgTime{pod=~\"$datanode\"}",
     "legendFormat": "Average Write Block Time"
    }
   ]
  },
  {
   "title": "Number of Read Blocks / 30 min",
   "type": "graph",
   "description": "Total number of read operations in 30 min.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Hadoop_DataNode_ReadBlockOpNumOps{pod=~\"$datanode\"}[30m])",
     "legendFormat": "Number of Read Blocks"
    }
   ]
  },
  {
   "title": "Read Block Avg Time",
   "type": "graph",
   "description": "Average Read block time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "Hadoop_DataNode_ReadBlockOpAvgTime{pod=~\"$datanode\"}",
     "legendFormat": "Average Read Block Time"
    }
   ]
  },
  {
   "title": "Log Statistics / 30min",
   "type": "graph",
   "description": "Log Statistics in 30 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Hadoop_DataNode_LogFatal{pod=~\"$datanode\"}[30m])",
     "legendFormat": "Fatal"
    },
    {
     "expr": "delta(Hadoop_DataNode_LogError{pod=~\"$datanode\"}[30m])",
     "legendFormat": "Error"
    },
    {
     "expr": "delta(Hadoop_DataNode_LogWarn{pod=~\"$datanode\"}[30m])",
     "legendFormat": "Warn"
    }
   ]
  }
 ]
}