images:
  adp-agent-config:
    url: ccr.ccs.tencentyun.com/tke-market/agent-config-server:3_2605062218_stable_v3.4.1.1_047477bf_private
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
