apiVersion: v2
name: lke-ti-ingress-controller
description: A Helm chart for TiGateway Ingress

type: application

version: 3.6.0

appVersion: 3.6.0

sources:
  - https://git.woa.com/ti2.0/ti-infrastructure/ti-ingress-controller.git
maintainers:
  - name: dawnsliu
