images:
  adp-apex:
    url: "{{ .Values.global.imageRegistry }}/tke-market/apex:4_2603280059_master_private_247b5729_private"
  apex-router:
    url: "{{ .Values.global.imageRegistry }}/tke-market/apex-router:5.8.0"
apex:
  database:
    type: mysql
    dsn: ''
    polling_interval: 5s
replicas: 1
