apiVersion: apps/v1
kind: Deployment
metadata:
  name: adp-kb-config
  namespace: {{ .Release.Namespace }}
  annotations:
    ti.cloud.tencent.com/resource-quota: unlimited
    configmap.reloader.stakater.com/reload: {{ .Release.Name }}-kb-config
    {{- if .Values.global.customAnnotations }}
    {{- range $key, $value := .Values.global.customAnnotations }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
  labels:
    app: adp-kb-config
    app.kubernetes.io/name: adp-kb-config
    {{- if .Values.global.customLabels }}
    {{- range $key, $value := .Values.global.customLabels }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
spec:
  {{- if eq .Values.global.clusterSize "minimal" }}
  replicas: 1
  {{- else if eq .Values.global.clusterSize "standard" }}
  replicas: 2
  {{- else }}
  replicas: 3
  {{- end }}
  selector:
    matchLabels:
      app: adp-kb-config
  template:
    metadata:
      labels:
        app: adp-kb-config
        {{- if .Values.global.customLabels }}
        {{- range $key, $value := .Values.global.customLabels }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
        {{- end }}
      {{- if .Values.global.customAnnotations }}
      annotations:
        {{- range $key, $value := .Values.global.customAnnotations }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
      {{- end }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - kb-config
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: GPUName
                    operator: DoesNotExist
            - weight: 50
              preference:
                matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - lke
      terminationGracePeriodSeconds: 90
      {{- if eq (include "needInitContainer" .) "true" }}
      serviceAccountName: adp-reader
      {{- end }}
      initContainers:
        {{- include "dependencyChecker.initContainer" . | nindent 8 }}
      containers:
        - env:
            - name: MKL_NUM_THREADS
              value: "2"
            - name: LOG_SPACES
              value: "2097152"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DEPLOYMENT_ENVIRONMENT
              value: TKE
            - name: NAME_SPACE
              value: default
            - name: ENV
              value: tcs
            - name: SERVER_LOG_LEVEL
              value: info
          image: {{ include "resolveImageUrl" (dict "url" (index .Values.images "adp-kb-config").url "context" .) }}
          imagePullPolicy: Always
          {{- if eq .Values.global.clusterSize "minimal" }}
          resources:
            limits:
              cpu: "500m"
              memory: "8Gi"
            requests:
              cpu: "125m"
              memory: "1Gi"
          {{- else if eq .Values.global.clusterSize "standard" }}
          resources:
            limits:
              cpu: "500m"
              memory: "8Gi"
            requests:
              cpu: "250m"
              memory: "2Gi"
          {{- else }}
          resources:
            limits:
              cpu: "1"
              memory: "8Gi"
            requests:
              cpu: "500m"
              memory: "2Gi"
          {{- end }}
          name: adp-kb-config
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /app/logs
              name: logdata
              subPathExpr: $(POD_NAME)
            - mountPath: /app/conf/trpc_go.yaml
              name: config
              subPath: trpc_go.yaml
            - mountPath: /app/conf/application.yaml
              name: config
              subPath: application.yaml
            - mountPath: /app/conf/main.yaml
              name: config
              subPath: main.yaml
            - mountPath: /app/conf/placeholder.yaml
              name: config
              subPath: placeholder.yaml
            - mountPath: /app/conf/whitelist.yaml
              name: config
              subPath: whitelist.yaml
            - mountPath: /app/conf/db_source_decode_key
              name: config
              subPath: db_source_decode_key
            - mountPath: /app/conf/kb-config_en-US.json
              name: config
              subPath: kb-config_en-US.json
            - mountPath: /app/conf/kb-config_zh-CN.json
              name: config
              subPath: kb-config_zh-CN.json
            - mountPath: /app/conf/error_en-US.json
              name: config
              subPath: error_en-US.json
            - mountPath: /app/conf/error_zh-CN.json
              name: config
              subPath: error_zh-CN.json
            - mountPath: /app/conf/infrastructure.yaml
              name: infrastructure
              subPath: infrastructure.yaml
      restartPolicy: Always
      volumes:
        {{- include "dependencyChecker.volumes" . | nindent 8 }}
        - hostPath:
            path: /etc/localtime
          name: localtime
        - hostPath:
            path: /data/ti-platform/log/adp-kb-config
            type: DirectoryOrCreate
          name: logdata
        - configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-kb-config
          name: config
        - configMap:
            defaultMode: 420
            name: infrastructure
          name: infrastructure
