apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ti.cloud.tencent.com/resource-quota: unlimited
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
    configmap.reloader.stakater.com/reload: {{ .Release.Name }}-platform-authenticator
========
    configmap.reloader.stakater.com/reload: {{ .Release.Name }}-resource-gallery
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
    {{- if .Values.global.customAnnotations }}
    {{- range $key, $value := .Values.global.customAnnotations }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
  labels:
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
    app: adp-platform-authenticator
    app.kubernetes.io/name: adp-platform-authenticator
========
    app: adp-resource-gallery
    app.kubernetes.io/name: adp-resource-gallery
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
    {{- if .Values.global.customLabels }}
    {{- range $key, $value := .Values.global.customLabels }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
  name: adp-platform-authenticator
========
  name: adp-resource-gallery
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
  namespace: {{ .Release.Namespace }}
spec:
  {{- if eq .Values.global.clusterSize "minimal" }}
  replicas: 1
  {{- else if eq .Values.global.clusterSize "standard" }}
  replicas: 2
  {{- else }}
  replicas: 3
  {{- end }}
  selector:
    matchLabels:
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
      app: adp-platform-authenticator
========
      app: adp-resource-gallery
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
  strategy : {}
  template:
    metadata:
      labels:
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
        app: adp-platform-authenticator
========
        app: adp-resource-gallery
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
        {{- if .Values.global.customLabels }}
        {{- range $key, $value := .Values.global.customLabels }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
        {{- end }}
      {{- if .Values.global.customAnnotations }}
      annotations:
        {{- range $key, $value := .Values.global.customAnnotations }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: platform-authenticator
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
                  - adp-platform-authenticator
========
                  - adp-resource-gallery
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
              topologyKey: kubernetes.io/hostname
            weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: GPUName
                    operator: DoesNotExist
            - weight: 50
              preference:
                matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - lke
      {{- if eq (include "needInitContainer" .) "true" }}
      serviceAccountName: adp-reader
      {{- end }}
      initContainers:
        {{- include "dependencyChecker.initContainer" . | nindent 8 }}
      containers:
        - env:
            - name: ADP-CHANNEL-ID
              value: "1"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DEPLOYMENT_ENVIRONMENT
              value: TKE
            - name: ENV
              value: tcs
            - name: SERVER_LOG_LEVEL
              value: info
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
            - name: ProductType
              value: {{ include "getProductType" . | quote }}
          image: {{(index .Values.images "adp-platform-authenticator").url}}
          imagePullPolicy: Always
          command: ["/app/bin/platform-authenticator", "-conf", "/app/conf/trpc_go.yaml"]
          name: adp-platform-authenticator
========
            - name: ADP_CHANNEL_ID
              value: "1"
            - name: ProductType
              value: {{ include "getProductType" . | quote }}
            {{- $channelUUID := include "getChannelUUID" . -}}
            {{- if $channelUUID }}
            - name: ADP_CHANNEL_UUID
              value: {{ $channelUUID | quote }}
            {{- end }}
          image: {{(index .Values.images "adp-resource-gallery").url}}
          imagePullPolicy: Always
          #command: ["sh","/usr/local/app/start.sh"]
          name: adp-resource-gallery
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
          {{- if eq .Values.global.clusterSize "minimal" }}
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
              memory: "512Mi"
========
              memory: "256Mi"
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
          {{- else if eq .Values.global.clusterSize "standard" }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "200m"
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
              memory: "512Mi"
========
              memory: "256Mi"
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
          {{- else }}
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "200m"
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
              memory: "512Mi"
========
              memory: "256Mi"
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
          {{- end }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 9090
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 9090
            timeoutSeconds: 2
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /app/logs
              name: logdata
              subPathExpr: $(POD_NAME)
            - mountPath: /app/conf/trpc_go.yaml
              name: config
              subPath: trpc_go.yaml
            - mountPath: /app/conf/application.yaml
              name: config
              subPath: application.yaml
            - mountPath: /app/conf/placeholder.yaml
              name: config
              subPath: placeholder.yaml
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
========
            - mountPath: /app/conf/biz_en-US.json
              name: config
              subPath: biz_en-US.json
            - mountPath: /app/conf/biz_zh-CN.json
              name: config
              subPath: biz_zh-CN.json
            - mountPath: /app/conf/errors_en-US.json
              name: config
              subPath: errors_en-US.json
            - mountPath: /app/conf/errors_zh-CN.json
              name: config
              subPath: errors_zh-CN.json
            - mountPath: /app/conf/model_mappings.json
              name: config
              subPath: model_mappings.json
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
            - mountPath: /app/conf/infrastructure.yaml
              name: infrastructure
              subPath: infrastructure.yaml
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        {{- include "dependencyChecker.volumes" . | nindent 8 }}
        - hostPath:
            path: /etc/localtime
          name: localtime
        - hostPath:
<<<<<<<< HEAD:incubator/adp/charts/adp-platform-authenticator/templates/deployment.yaml
            path: /data/ti-platform/log/adp-platform-authenticator
========
            path: /data/ti-platform/log/adp-resource-gallery
>>>>>>>> upstream/main:incubator/adp/charts/adp-resource-gallery/templates/deployment.yaml
            type: DirectoryOrCreate
          name: logdata
        - configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-platform-authenticator
          name: config

        - configMap:
            defaultMode: 420
            name: infrastructure
          name: infrastructure
