images:
  adp-plugin-code-kernel:
    url: "{{ .Values.global.imageRegistry }}/tke-market/kernel:v20260325.0-amd64-py3.10	"
cos_proxy_url: http://plugin-cos-util.{{ .Release.Namespace }}.svc.cluster.local:8080
adp-plugin-code-kernel:
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
replicas: 1
