images:
  lke-ti-perm-auth-proxy:
    url: "{{ .Values.global.imageRegistry }}/tke-market/ti_auth_proxy:master_private_503f8751_20260818"
resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
