images:
  adp-ai-gateway:
    url: "{{ .Values.global.imageRegistry }}/tke-market/ai-gateway:20_2604271939_stable_v3.4.1.1_intl_c829fcce_private"
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
