kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-app-channel-token
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |
    task_conf:
      refreshTokenTime: 5900
      getOutdatedLimit: 2 # 每次取几条数据
      concurrentWorkNum: 1 # 并发数
      lockTime: 3900 # 上锁时间
      retryRefreshInterval: 5900
    wechat_conf:
      componentAppID: ${COMPONENT_APP_ID}  #微信后台的应用appid   公有云用的自己的，这里需要填用户的  tokenFreqNum: 1
      useRedisCache: true
      channelHost: {{ .Values.global.scheme }}://{{ .Values.global.clb }}  #专有云代理回调域名；若用户请求的 Host 与此一致，表示未配自有代理，Host 会被替换为 qyapi.weixin.qq.com 走公网
    domain_verify_rule : ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}(:\d+)?$

  client.yaml: |
    client:
      namespace: ${POD_NAMESPACE}
      filter:
        - cle-route-propagator
      service:
        - name: tdsql.tcadp.channel
          target: "dsn://${INFRA_MIDDLEWARES_DB_0_USER}:${INFRA_MIDDLEWARES_DB_0_PASSWORD}@tcp(${INFRA_MIDDLEWARES_DB_0_HOST}:${INFRA_MIDDLEWARES_DB_0_PORT})/db_llm_robot?charset=utf8mb4&timeout=1s&parseTime=true&interpolateParams=true&loc=Local"
        - name: redis.qbot.admin
          network: tcp
          protocol: redis
          target: "ip://${INFRA_MIDDLEWARES_REDIS_0_HOSTS}:6379/2"
          password: ${INFRA_MIDDLEWARES_REDIS_0_PASSWORD}
        - name: wx.nginx
          target: ip://adp-app-channel-proxy.{{ .Release.Namespace }}.svc.cluster.local:8000
          network: tcp
          protocol: http
          timeout: 20000

  placeholder.yaml: |
    NAMESPACE: Production
    ENV_NAME: formal
    RAINBOW_GROUP: channel-token-svr
    RAINBOW_ENV_NAME: formal
    TRPC_KEP_CHANNEL_TOKEN_SVR_CHANNELTOKENSERVICE_TOKEN:
    TRPC_KEP_CHANNEL_TOKEN_SVR_CHANNELTOKENSERVICE_HTTP_TOKEN:

    COMPONENT_APP_ID: "{{ dig "wechat" "componentAppId" "" .Values.global }}"

    IS_PRIVATE: true
    NGINX_FORWARD_PROXY_TARGET: ip://adp-app-channel-proxy.{{ .Release.Namespace }}.svc.cluster.local:8000

  trpc_go.yaml: |
    global:                             #全局配置
      namespace: ${POD_NAMESPACE}        #环境类型，分正式production和非正式development两种类型
      env_name: formal                        #环境名称，非正式环境下多环境的名称
      enable_set: false                 #是否启用set
      full_set_name: adp                #set名
      local_ip: ${POD_IP}
      container_name: ${POD_NAME}

    server:                                            #服务端配置
      app: adp                                        #业务的应用名
      server: app-channel-token                             #进程服务名
      bin_path: /usr/local/trpc/bin/                   #二进制可执行文件和框架配置文件所在路径
      conf_path: /usr/local/trpc/conf/                 #业务配置文件所在路径
      data_path: /usr/local/trpc/data/                 #业务数据文件所在路径
      filter:                                          #针对所有service处理函数前后的拦截器列表
        - recovery
        - debuglog
        - i18n-adp
        - cle-route-propagator
        - opentelemetry
      admin:
        port: 8081
      service:                                         #业务服务提供的service，可以有多个
        - name: trpc.KEP.channel-token-svr.ChannelTokenService
          port: 8000
          network: tcp
          protocol: trpc
          timeout: 0
          server_async: true
          idletime: 600000
        - name: trpc.KEP.channel-token-svr.HTTP
          port: 8001
          network: tcp
          protocol: http_no_protocol
          timeout: 3000
        - name: trpc.KEP.channel-token-svr.wechat-app-timer
          port: 9001
          network: "*/10 * * * *"
          protocol: timer
          timeout: 4000
        - name: trpc.KEP.channel-token-svr.wecom-agent-timer
          port: 9003
          network: "*/10 * * * *"
          protocol: timer
          timeout: 4000
        - name: trpc.KEP.channel-token-svr.dingtalk-agent-timer
          ip: ${POD_IP}
          port: 9004
          network: "*/10 * * * *"
          protocol: timer
          timeout: 4000
    plugins:                                          #插件配置
      telemetry:
        opentelemetry:
          addr: {{ ((.Values.global.observability).apm).otlp | default "" }}
          tenant_id: adp
          sampler:
            fraction: 1
          traces:
            disable_trace_body: false
          metrics:
            {{- if ((.Values.global.observability).apm).registry }}
            registry_endpoints: ["{{ .Values.global.observability.apm.registry}}"]
            {{- end }}
          logs:
            enabled: true
            level: "debug"
            trace_log_mode: "disable"
          {{- if ((.Values.global.observability).apm).attributes }}
          attributes:
            {{- range $key, $value := .Values.global.observability.apm.attributes }}
          - key: {{ $key }}
            value: {{ $value }}
            {{- end }}
          {{- end }}
      log:
        default:
          - writer: console
            level: info
            formatter: json
            formatter_config:
              time_cmt: "2006-01-02T15:04:05.999999999Z07:00"
              time_key: time
              level_key: level
              name_key: name
              caller_key: caller
              message_key: message
          - writer: file
            level: info
            formatter: json
            formatter_config:
              time_cmt: "2006-01-02T15:04:05.999999999Z07:00"
              time_key: time
              level_key: level
              name_key: name
              caller_key: caller
              message_key: message
              stacktrace_key: stackTrace
            writer_config:
              filename: /app/log/trpc.log
              write_mode: 2
              roll_type: size
              max_size: 200
              max_backups: 10
              compress: false
      config:
        file:
          providers:
            - name: rainbow
              path: /app/conf/
            - name: global
              appid: ${RAINBOW_APP_ID}
              group: global
              type: kv
              env_name: ${RAINBOW_ENV_NAME}
              timeout: 2000
              enable_client_provider: true
      registry: #服务注册配置
      selector: #针对用户自定义的selector的配置
        polaris: #针对polaris整体api的内部配置
          protocol: grpc                              #名字服务远程交互协议类型


    client:
      namespace: ${POD_NAMESPACE}
      filter:
        - cle-route-propagator
      service:
        - name: tdsql.tcadp.channel
          target: "dsn://${INFRA_MIDDLEWARES_DB_0_USER}:${INFRA_MIDDLEWARES_DB_0_PASSWORD}@tcp(${INFRA_MIDDLEWARES_DB_0_HOST}:${INFRA_MIDDLEWARES_DB_0_PORT})/db_llm_robot?charset=utf8mb4&timeout=1s&parseTime=true&interpolateParams=true&loc=Local"
        - name: redis.qbot.admin
          network: tcp
          protocol: redis
          target: "ip://${INFRA_MIDDLEWARES_REDIS_0_HOSTS}:6379/2"
          password: ${INFRA_MIDDLEWARES_REDIS_0_PASSWORD}
        - name: wx.nginx
          target: ip://adp-app-channel-proxy.{{ .Release.Namespace }}.svc.cluster.local:8000
          network: tcp
          protocol: http
          timeout: 20000
