images:
  adp-agent-exec:
    url: "{{ .Values.global.imageRegistry }}/tke-market/agent-exec:18_2607302052_stable_iaas_v4.0.3.0_bcdd034f_private"
resources:
  limits:
    cpu: 4
    memory: 16Gi
  requests:
    cpu: 2
    memory: 8Gi
replicas: 1
