images:
  adp-agent-exec:
    url: "{{ .Values.global.imageRegistry }}/tke-market/agent-exec:8_2606132001_stable_iaas_cos_2b31ec76_private"
resources:
  limits:
    cpu: 4
    memory: 16Gi
  requests:
    cpu: 2
    memory: 8Gi
replicas: 1
