images:
  adp-agent-exec:
    url: "{{ .Values.global.imageRegistry }}/tke-market/agent-exec:14_2607271708_stable_iaas_v4.0.3.0_403ec660_private"
resources:
  limits:
    cpu: 4
    memory: 16Gi
  requests:
    cpu: 2
    memory: 8Gi
replicas: 1
