apiVersion: apps/v1
kind: Deployment
metadata:
  name: adp-plugin-exec
  namespace: {{ .Release.Namespace }}
  annotations:
    ti.cloud.tencent.com/resource-quota: unlimited
    configmap.reloader.stakater.com/reload: {{ .Release.Name }}-plugin-exec
    {{- if .Values.global.customAnnotations }}
    {{- range $key, $value := .Values.global.customAnnotations }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
  labels:
    app: adp-plugin-exec
    app.kubernetes.io/name: adp-plugin-exec
    {{- if .Values.global.customLabels }}
    {{- range $key, $value := .Values.global.customLabels }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
spec:
  {{- if eq .Values.global.clusterSize "minimal" }}
  replicas: 1
  {{- else if eq .Values.global.clusterSize "standard" }}
  replicas: 2
  {{- else }}
  replicas: 3
  {{- end }}
  selector:
    matchLabels:
      app: adp-plugin-exec
  template:
    metadata:
      labels:
        app: adp-plugin-exec
        {{- if .Values.global.customLabels }}
        {{- range $key, $value := .Values.global.customLabels }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
        {{- end }}
      {{- if .Values.global.customAnnotations }}
      annotations:
        {{- range $key, $value := .Values.global.customAnnotations }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
      {{- end }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - adp-plugin-exec
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: GPUName
                    operator: DoesNotExist
            - weight: 50
              preference:
                matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - lke
      terminationGracePeriodSeconds: 90
      {{- if eq (include "needInitContainer" .) "true" }}
      serviceAccountName: adp-reader
      {{- end }}
      initContainers:
        {{- include "dependencyChecker.initContainer" . | nindent 8 }}
      containers:
        - env:
            - name: MKL_NUM_THREADS
              value: "2"
            - name: LOG_SPACES
              value: "2097152"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DEPLOYMENT_ENVIRONMENT
              value: TKE
            - name: NAME_SPACE
              value: default
            - name: ENV
              value: tcs
            - name: SERVER_LOG_LEVEL
              value: info
          image: {{(index .Values.images "adp-plugin-exec").url}}
          imagePullPolicy: Always
          name: adp-plugin-exec
          #command: ["sh","-c", "crond start; touch /var/log/log.txt && tail -f /var/log/log.txt"]
          # command: ["sh","/app/bin/start.sh"]
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 8000
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 30
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 8000
            timeoutSeconds: 2
          {{- if eq .Values.global.clusterSize "minimal" }}
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          {{- else if eq .Values.global.clusterSize "standard" }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          {{- else }}
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          {{- end }}
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /app/logs
              name: logdata
              subPathExpr: $(POD_NAME)
            - mountPath: /app/conf/trpc_go.yaml
              name: config
              subPath: trpc_go.yaml
            - mountPath: /app/conf/placeholder.yaml
              name: config
              subPath: placeholder.yaml
            - mountPath: /app/conf/main.yaml
              name: config
              subPath: main.yaml
            - mountPath: /app/conf/mcp_server_1.yaml
              name: config
              subPath: mcp_server_1.yaml
            - mountPath: /app/conf/mcp_server_2.yaml
              name: config
              subPath: mcp_server_2.yaml
            - mountPath: /app/conf/stateless_mcp_server_1.yaml
              name: config
              subPath: stateless_mcp_server_1.yaml
            - mountPath: /app/conf/plugin-exec_en-US.json
              name: config
              subPath: plugin-exec_en-US.json
            - mountPath: /app/conf/plugin-exec_zh-CN.json
              name: config
              subPath: plugin-exec_zh-CN.json
            - mountPath: /app/conf/error_en-US.json
              name: config
              subPath: error_en-US.json
            - mountPath: /app/conf/error_zh-CN.json
              name: config
              subPath: error_zh-CN.json
            - mountPath: /app/conf/scurl.yaml
              name: rainbow-comm
              subPath: scurl.yaml
            - mountPath: /app/conf/infrastructure.yaml
              name: infrastructure
              subPath: infrastructure.yaml
        - env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: {{(index .Values.images "adp-plugin-exec-sidecar").url}}
          imagePullPolicy: Always
          name: markmap-sidecar
          # command: ["bash","/usr/local/bin/start.sh"]
          # command: ["bash","-c","while true; do sleep 30; done"]
          ports:
            - containerPort: 7001
              name: sidecar-7001
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '70'
          {{- if eq .Values.global.clusterSize "minimal" }}
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          {{- else if eq .Values.global.clusterSize "standard" }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          {{- else }}
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          {{- end }}
          securityContext:
            capabilities:
              add:
                - SYS_RESOURCE
                - NET_ADMIN
                - SYS_ADMIN
                - IPC_LOCK
                - SYS_PTRACE
            privileged: false
          stdin: true
          tty: true
          #volumeMounts:
          #  - mountPath: /app/logs
          #    name: markmap-sidecar-log
          #  - mountPath: /usr/local/
          #    name: markmap-public
      restartPolicy: Always
      volumes:
        {{- include "dependencyChecker.volumes" . | nindent 8 }}
        - hostPath:
            path: /etc/localtime
          name: localtime
        - hostPath:
            path: /data/ti-platform/log/adp-plugin-exec
            type: DirectoryOrCreate
          name: logdata
        #- hostPath:
        #    path: /data/ti-platform/log/markmap-sidecar
        #    type: DirectoryOrCreate
        #  name: markmap-sidecar-log
        #- hostPath:
        #    path: /data/markmap
        #    type: DirectoryOrCreate
        #  name: markmap-public
        - configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-plugin-exec
          name: config
        - configMap:
            defaultMode: 420
            name: rainbow-comm
          name: rainbow-comm

        - configMap:
            defaultMode: 420
            name: infrastructure
          name: infrastructure
