{
 "title": "Kudu",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kudu_master",
    "label": "Kudu_Master",
    "query": "label_values(kudu_server_block_manager_blocks_open_reading__value,pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "state",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kudu_tablet_state__value{pod=\"$kudu_master\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "time_since_last_leader_heartbeat",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "kudu_tablet_time_since_last_leader_heartbeat__value{pod=\"$kudu_master\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "log_block_manager_full_containers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kudu_server_log_block_manager_full_containers__value{pod=\"$kudu_master\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TSHeartbeat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_TSHeartbeat__percentile_99_99{pod=\"$kudu_master\"}",
     "legendFormat": "percentile_99_99"
    },
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_TSHeartbeat__max{pod=\"$kudu_master\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_TSHeartbeat__min{pod=\"$kudu_master\"}",
     "legendFormat": "min"
    },
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_TSHeartbeat__mean{pod=\"$kudu_master\"}",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "blocks_open_reading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kudu_server_block_manager_blocks_open_reading__value{pod=\"$kudu_master\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "on_disk_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kudu_tablet_on_disk_size__value{pod=\"$kudu_master\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "file_cache_misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kudu_server_file_cache_misses__value{pod=\"$kudu_master\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "op_prepare_queue_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kudu_tablet_op_prepare_queue_time__percentile_99_99{pod=\"$kudu_master\"}",
     "legendFormat": "percentile_99_99"
    },
    {
     "expr": "kudu_tablet_op_prepare_queue_time__max{pod=\"$kudu_master\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kudu_tablet_op_prepare_queue_time__min{pod=\"$kudu_master\"}",
     "legendFormat": "min"
    },
    {
     "expr": "kudu_tablet_op_prepare_queue_time__mean{pod=\"$kudu_master\"}",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "op_prepare_run_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kudu_tablet_op_prepare_run_time__percentile_99_99{pod=\"$kudu_master\"}",
     "legendFormat": "percentile_99_99"
    },
    {
     "expr": "kudu_tablet_op_prepare_run_time__max{pod=\"$kudu_master\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kudu_tablet_op_prepare_run_time__min{pod=\"$kudu_master\"}",
     "legendFormat": "min"
    },
    {
     "expr": "kudu_tablet_op_prepare_run_time__mean{pod=\"$kudu_master\"}",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "delta_file_lookups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kudu_tablet_delta_file_lookups__value{pod=\"$kudu_master\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "op_prepare_queue_length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kudu_tablet_op_prepare_queue_length__percentile_99_99{pod=\"$kudu_master\"}",
     "legendFormat": "percentile_99_99"
    },
    {
     "expr": "kudu_tablet_op_prepare_queue_length__max{pod=\"$kudu_master\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kudu_tablet_op_prepare_queue_length__min{pod=\"$kudu_master\"}",
     "legendFormat": "min"
    },
    {
     "expr": "kudu_tablet_op_prepare_queue_length__mean{pod=\"$kudu_master\"}",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "delta_minor_compact_rs_duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kudu_tablet_delta_minor_compact_rs_duration__percentile_99_99{pod=\"$kudu_master\"}",
     "legendFormat": "percentile_99_99"
    },
    {
     "expr": "kudu_tablet_delta_minor_compact_rs_duration__max{pod=\"$kudu_master\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kudu_tablet_delta_minor_compact_rs_duration__min{pod=\"$kudu_master\"}",
     "legendFormat": "min"
    },
    {
     "expr": "kudu_tablet_delta_minor_compact_rs_duration__mean{pod=\"$kudu_master\"}",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "delta_major_compact_rs_duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kudu_tablet_delta_major_compact_rs_duration__percentile_99_99{pod=\"$kudu_master\"}",
     "legendFormat": "percentile_99_99"
    },
    {
     "expr": "kudu_tablet_delta_major_compact_rs_duration__max{pod=\"$kudu_master\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kudu_tablet_delta_major_compact_rs_duration__min{pod=\"$kudu_master\"}",
     "legendFormat": "min"
    },
    {
     "expr": "kudu_tablet_delta_major_compact_rs_duration__mean{pod=\"$kudu_master\"}",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "kudu_server_handler_latency_kudu_master_MasterService_ConnectToMaster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_ConnectToMaster__percentile_99_99{pod=\"$kudu_master\"}",
     "legendFormat": "percentile_99_99"
    },
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_ConnectToMaster__max{pod=\"$kudu_master\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_ConnectToMaster__min{pod=\"$kudu_master\"}",
     "legendFormat": "min"
    },
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_ConnectToMaster__mean{pod=\"$kudu_master\"}",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "block_manager_blocks_open_reading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kudu_server_block_manager_blocks_open_reading__value{pod=\"$kudu_master\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "handler_latency_kudu_master_MasterService_Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_Ping__percentile_99_99{pod=\"$kudu_master\"}",
     "legendFormat": "percentile_99_99"
    },
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_Ping__max{pod=\"$kudu_master\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_Ping__min{pod=\"$kudu_master\"}",
     "legendFormat": "min"
    },
    {
     "expr": "kudu_server_handler_latency_kudu_master_MasterService_Ping__mean{pod=\"$kudu_master\"}",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "glog_messages / 30m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(kudu_server_glog_info_messages__value{pod=\"$kudu_master\"}[30m])",
     "legendFormat": "info"
    },
    {
     "expr": "delta(kudu_server_glog_warning_messages__value{pod=\"$kudu_master\"}[30m])",
     "legendFormat": "warning"
    },
    {
     "expr": "delta(kudu_server_glog_error_messages__value{pod=\"$kudu_master\"}[30m])",
     "legendFormat": "error"
    }
   ]
  }
 ]
}