{
 "title": "HDFS NameNode",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namenode",
    "label": "NameNode",
    "query": "label_values(Hadoop_NameNode_HAState,pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "FS State",
   "type": "singlestat",
   "description": "Current state of the file system: Safemode or Operational",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_FSState{pod=\"$namenode\"}"
    }
   ]
  },
  {
   "title": "HA State",
   "type": "singlestat",
   "description": "(HA-only) Current state of the NameNode: initializing or active or standby or stopping state",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_HAState{pod=\"$namenode\"}"
    }
   ]
  },
  {
   "title": "Blocks Total",
   "type": "singlestat",
   "description": "Current number of allocated blocks in the system",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_BlocksTotal{pod=~\"$namenode\", name=~\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "Missing Blocks",
   "type": "singlestat",
   "description": "Current number of missing blocks",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_MissingBlocks{pod=\"$namenode\"}"
    }
   ]
  },
  {
   "title": "Block Capacity",
   "type": "singlestat",
   "description": "Current number of block capacity",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_BlockCapacity{pod=~\"$namenode\", name=~\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "Corrupt Blocks",
   "type": "singlestat",
   "description": "Current number of blocks with corrupt replicas.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_CorruptBlocks{pod=~\"$namenode\", name=~\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "Num Live Data Nodes",
   "type": "singlestat",
   "description": "Number of datanodes which are currently live",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_NumLiveDataNodes{pod=~\"$namenode\", name=~\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "Num Dead Data Nodes",
   "type": "singlestat",
   "description": "Number of datanodes which are currently dead",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_NumDeadDataNodes{pod=~\"$namenode\", name=~\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "Files Total",
   "type": "singlestat",
   "description": "Current number of files and directories",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_FilesTotal{pod=~\"$namenode\", name=~\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "Capacity Total",
   "type": "singlestat",
   "description": "Current raw capacity of DataNode",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_CapacityTotal{pod=\"$namenode\",name=\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "singlestat",
   "description": "Current used capacity across all DataNodes",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_CapacityUsed{pod=\"$namenode\",name=\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "Capacity Used Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "Hadoop_NameNode_CapacityUsed{pod=\"$namenode\",name=\"FSNamesystem\"}*100/Hadoop_NameNode_CapacityTotal{pod=\"$namenode\",name=\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "FsImage Load Time",
   "type": "singlestat",
   "description": "Time loading FS Image at startup in milliseconds",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_FsImageLoadTime{pod=~\"$namenode\"}"
    }
   ]
  },
  {
   "title": "Total Load",
   "type": "singlestat",
   "description": "Current number of connections",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_TotalLoad{pod=~\"$namenode\", name=~\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "Lock Queue Length",
   "type": "singlestat",
   "description": "Number of threads waiting to acquire FSNameSystem lock",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_LockQueueLength{pod=~\"$namenode\", name=~\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "singlestat",
   "description": "Total GC count",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_GcCount{pod=~\"$namenode\"}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "singlestat",
   "description": "Total GC time in msec",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_NameNode_GcTimeMillis{pod=~\"$namenode\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{pod_name=~\"kdl-hadoop-hdfs-nn-(\\\\d+)\"}[5m])*100) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"kdl-hadoop-hdfs-nn-(\\\\d+)\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_MemHeapUsedM{pod=~\"$namenode\"}",
     "legendFormat": "Current heap memory used"
    },
    {
     "expr": "Hadoop_NameNode_MemHeapCommittedM{pod=~\"$namenode\"}",
     "legendFormat": "Current heap memory committed"
    },
    {
     "expr": "Hadoop_NameNode_MemHeapMaxM{pod=~\"$namenode\"}",
     "legendFormat": "Max heap memory "
    }
   ]
  },
  {
   "title": "JVM Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_MemNonHeapUsedM{pod=~\"$namenode\"}",
     "legendFormat": "Current non-heap memory used"
    },
    {
     "expr": "Hadoop_NameNode_MemNonHeapCommittedM{pod=~\"$namenode\"}",
     "legendFormat": "Current non-heap memory committed"
    },
    {
     "expr": "Hadoop_NameNode_MemNonHeapMaxM{pod=~\"$namenode\"}",
     "legendFormat": "Max non-heap memory "
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_ThreadsNew{pod=~\"$namenode\"}",
     "legendFormat": "NEW threads"
    },
    {
     "expr": "Hadoop_NameNode_ThreadsRunnable{pod=~\"$namenode\"}",
     "legendFormat": "RUNNABLE threads"
    },
    {
     "expr": "Hadoop_NameNode_ThreadsBlocked{pod=~\"$namenode\"}",
     "legendFormat": "BLOCKED threads"
    },
    {
     "expr": "Hadoop_NameNode_ThreadsWaiting{pod=~\"$namenode\"}",
     "legendFormat": "WAITING threads"
    },
    {
     "expr": "Hadoop_NameNode_ThreadsTimedWaiting{pod=~\"$namenode\"}",
     "legendFormat": "TIMED_WAITING threads"
    },
    {
     "expr": "Hadoop_NameNode_ThreadsTerminated{pod=~\"$namenode\"}",
     "legendFormat": "TERMINATED threads"
    }
   ]
  },
  {
   "title": "Log Statistics / 30min",
   "type": "graph",
   "description": "Log Statistics in 30 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Hadoop_NameNode_LogFatal{pod=~\"$namenode\"}[30m])",
     "legendFormat": "Fatal"
    },
    {
     "expr": "delta(Hadoop_NameNode_LogError{pod=~\"$namenode\"}[30m])",
     "legendFormat": "Error"
    },
    {
     "expr": "delta(Hadoop_NameNode_LogWarn{pod=~\"$namenode\"}[30m])",
     "legendFormat": "Warn"
    }
   ]
  },
  {
   "title": "GC Statistics / 15min",
   "type": "graph",
   "description": "GC count in 15 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Hadoop_NameNode_GcCount{pod=~\"$namenode\"}[15m])",
     "legendFormat": "GC Count"
    },
    {
     "expr": "delta(Hadoop_NameNode_GcNumWarnThresholdExceeded{pod=~\"$namenode\"}[15m])",
     "legendFormat": "WarnThresholdExceeded"
    },
    {
     "expr": "delta(Hadoop_NameNode_GcNumInfoThresholdExceeded{pod=~\"$namenode\"}[15m])",
     "legendFormat": "InfoThresholdExceeded"
    }
   ]
  },
  {
   "title": "Block Report Num Ops",
   "type": "graph",
   "description": "Total number of processing block reports from DataNode",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_BlockReportNumOps{pod=~\"$namenode\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block Report Avg Time (ms)",
   "type": "graph",
   "description": "Average time of processing block reports in milliseconds",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_BlockReportAvgTime{pod=~\"$namenode\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}