kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-platform-authenticator
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |
    is_private: ${IS_PRIVATE}

    memory_cache_config: ${MEMORY_CACHE_CONFIG}

    lru_cache_config: ${LRU_CACHE_CONFIG}

    casbin_conf: ${CASBIN_CONF}

    resc_casbin_conf: ${RESC_CASBIN_CONF}

    company_action_map: ${COMPANY_ACTION_MAP}

    edit_resc_permission_map: ${EDIT_RESC_PERMISSION_MAP}

    view_resc_permission_map: ${VIEW_RESC_PERMISSION_MAP}

    no_resc_permission_map: ${NO_RESC_PERMISSION_MAP}

    disable_permission_list: ${DISABLE_PERMISSION_LIST}

    auth_action_permission_ids_map: ${AUTH_ACTION_PERMISSION_IDS_MAP}

    default_granted_permission_ids: ${DEFAULT_GRANTED_PERMISSION_IDS}

    ti_auth_account_conf: ${TI_AUTH_ACCOUNT_CONF}

    role_conf:
      business_role_name: 管理员
      business_role_description: 主账号管理员角色
      role_id_salt: superadmin

  placeholder.yaml: |
    #trpc_go.yaml
    NAMESPACE: Production
    ENV_NAME: formal
    RAINBOW_APP_ID: 3f090873-420d-4575-b9d2-cf6a72980a33
    RAINBOW_ENV_NAME: formal
    RAINBOW_GROUP: platform-authenticator

    TI_AUTH_ACCOUNT_TARGET: dns://ti-perm-auth.{{ .Release.Namespace }}.svc.cluster.local:8081

    #application.yaml
    IS_PRIVATE: true
    MEMORY_CACHE_CONFIG:
      PermissionInfo:
        cache_ttl: 3600s
        cache_capacity: 1
        shard_num: 1
        entry_size: 1000
      RescPermissionInfo:
        cache_ttl: 3600s
        cache_capacity: 1
        shard_num: 1
        entry_size: 1000
      UinRole:
        cache_ttl: 3600s
        cache_capacity: 150
        shard_num: 32
        entry_size: 409600
      RescRolePermission:
        cache_ttl: 3600s
        cache_capacity: 400
        shard_num: 16
        entry_size: 20480000
      default:
        cache_ttl: 3600s
        cache_capacity: 150
    LRU_CACHE_CONFIG:
      redis_exp_time_in_second: 86400
      redis_refresh_time_wait_in_second: 3
      lru_capacity: 10000
      exp_time_in_second: 86400
      clear_delay_time_in_second: 60
      load_batch_size: 100
      load_conn_num: 10
    CASBIN_CONF:
      casbin_model:
        request_definition: sub, dom, obj, act, app
        policy_definition:  sub, dom, obj, act, app
        role_definition: _, _, _
        policy_effect: some(where (p.eft == allow))
        matchers: r.sub==p.sub && r.dom == p.dom && r.app == p.app && regexMatch(r.obj, p.obj) && regexMatch(r.act,p.act)
    RESC_CASBIN_CONF:
      casbin_model:
        request_definition: sub, res_t, res, act
        policy_definition:  sub, res_t, res, act
        role_definition: _, _, _
        policy_effect: some(where (p.eft == allow))
        matchers: r.sub==p.sub && r.res_t == p.res_t && regexMatch(r.res, p.res) && regexMatch(r.act,p.act)
    COMPANY_ACTION_MAP:
      lke-space-admin-role:
        - CreateSpace
        - DeleteSpace
        - ModifySpace
        - ListSpace
    EDIT_RESC_PERMISSION_MAP:
      app:  adpAppEdit
      knowledge:  adpKnowledgeBaseEdit
      plugin:  adpPluginCenterEdit
      prompt_template:  adpPromptTemplateEdit
      widget:  adpWidgetCenterEdit
      openclaw: adpOpenClawEdit
      skill: adpSkillsCenterEdit
    VIEW_RESC_PERMISSION_MAP:
      app:  adpAppView
      knowledge:  adpKnowledgeBaseView
      plugin:  adpPluginCenterView
      prompt_template:  adpPromptTemplateView
      widget:  adpWidgetCenterView
      openclaw: adpOpenClawView
      skill: adpSkillsCenterView
    NO_RESC_PERMISSION_MAP:
      app: adpAppNoPermission
      knowledge: adpKnowledgeBaseNoPermission
      plugin: adpPluginCenterNoPermission
      prompt_template: adpPromptTemplateNoPermission
      widget: adpWidgetCenterNoPermission
      openclaw: adpOpenClawNoPermission
      skill: adpSkillsCenterNoPermission
    DISABLE_PERMISSION_LIST:
      - lkeApp.basic
      - lkeApp.copyApp
      - lkeApp.deleteApp
      - lkeApp.listApp
      - lkeApp.modifyAppQuota
      - lkeClassify
      - lkeClassify.config
      - lkeClassify.config.basic
      - lkeClassify.config.chat
      - lkeClassify.config.model
      - lkeClassify.config.model.version
      - lkeClassify.config.tag
      - lkeClassify.release
      - lkeClassify.release.call
      - lkeClassify.release.call.reception
      - lkeClassify.release.call.secret
      - lkeClassify.release.do
      - lkeRepository
      - lkeRepository.config
      - lkeRepository.config.AdvancedSettings
      - lkeRepository.config.AdvancedSettings.synonyms
      - lkeRepository.config.basic
      - lkeRepository.config.chat
      - lkeRepository.config.knowledge
      - lkeRepository.config.knowledge.db
      - lkeRepository.config.knowledge.doc
      - lkeRepository.config.knowledge.qa
      - lkeRepository.config.knowledge.qaTopN
      - lkeRepository.config.knowledge.replyFlexibility
      - lkeRepository.config.knowledge.searchEngine
      - lkeRepository.config.knowledge.searchStrategy
      - lkeRepository.config.knowledge.tableEnhancement
      - lkeRepository.config.knowledge.taskFlow
      - lkeRepository.config.model
      - lkeRepository.config.model.historyLimit
      - lkeRepository.config.model.historyRecordLimit
      - lkeRepository.config.model.version
      - lkeRepository.config.output
      - lkeRepository.config.output.generalKnowledge
      - lkeRepository.config.output.method
      - lkeRepository.config.pattern
      - lkeRepository.config.plugin
      - lkeRepository.evaluateBatch
      - lkeRepository.manage
      - lkeRepository.manage.db
      - lkeRepository.manage.doc
      - lkeRepository.manage.doc.download
      - lkeRepository.manage.knowledgeTag
      - lkeRepository.manage.qa
      - lkeRepository.manage.qa.export
      - lkeRepository.manage.taskFlow
      - lkeRepository.release
      - lkeRepository.release.call
      - lkeRepository.release.call.reception
      - lkeRepository.release.call.secret
      - lkeRepository.release.channel
      - lkeRepository.release.do
      - lkeRepository.release.do.create
      - lkeRepository.test
      - lkeRepository.unsatisfied
      - lkeRepository.workflow
      - lkeRepository.workflow.manage
      - lkeShareKG.listShareKG
      - lkeShareKG.manager
      - lkeSummary
      - lkeSummary.config
      - lkeSummary.config.basic
      - lkeSummary.config.chat
      - lkeSummary.config.model
      - lkeSummary.config.model.version
      - lkeSummary.config.output
      - lkeSummary.config.output.method
      - lkeSummary.config.output.requirement
      - lkeSummary.release
      - lkeSummary.release.call
      - lkeSummary.release.call.reception
      - lkeSummary.release.call.secret
      - lkeSummary.release.do

    AUTH_ACTION_PERMISSION_IDS_MAP:
      ListModel:
        - lkeCorpAssistant
      CreateCorpAssistantVariable:
        - lkeCorpAssistant
      ModifyCorpAssistantVariable:
        - lkeCorpAssistant
      DeleteCorpAssistantVariable:
        - lkeCorpAssistant
      DescribeCorpAssistantVariableList:
        - lkeCorpAssistant
      CreateCorpAssistantAgent:
        - lkeCorpAssistant
      ModifyCorpAssistantAgent:
        - lkeCorpAssistant
      DeleteCorpAssistantAgent:
        - lkeCorpAssistant
      DescribeCorpAssistantAgent:
        - lkeCorpAssistant
      CreateCorpAssistantConversation:
        - lkeCorpAssistant
      DescribeCorpAssistantConversationList:
        - lkeCorpAssistant
      DeleteCorpAssistantConversation:
        - lkeCorpAssistant
      ModifyCorpAssistantConversation:
        - lkeCorpAssistant
      DescribeCorpAssistantConversation:
        - lkeCorpAssistant
      DescribeCorpAssistantConversationMessageList:
        - lkeCorpAssistant
      CreateCorpAssistantWebSocketToken:
        - lkeCorpAssistant
      CreateCorpAssistantWorkspaceCredential:
        - lkeCorpAssistant
      DescribeSkillCategoryList:
        - lkeCorpAssistant
      DescribeSkillSummaryList:
        - lkeCorpAssistant
      DescribeKnowledgeBaseList:
        - lkeCorpAssistant
      ListPlugin:
        - lkeCorpAssistant

    DEFAULT_GRANTED_PERMISSION_IDS:
      - lkeCorpAssistant

    TI_AUTH_ACCOUNT_CONF:
      describe_self_depts: /DescribeSelfDepts

    ROLE_CONF:
      business_role_name: 管理员
      business_role_description: 主账号管理员角色
      role_id_salt: superadmin
  trpc_go.yaml: |
    global:
      namespace: ${NAMESPACE} #环境类型，分正式production和非正式development两种类型
      env_name: ${ENV_NAME} #环境名称，非正式环境下多环境的名称
      enable_set: ${ENABLE_SET} #是否启用set
      full_set_name: ${FULL_SET_NAME} #set名
      local_ip: ${POD_IP}
      container_name: ${POD_NAME}
    server:
      app: adp
      server: platform-authenticator
      filter:
        - recovery
        - i18n-adp
        - cle-route-propagator
        - opentelemetry
      stream_filter:
        - opentelemetry
      admin:
        ip: ${POD_IP}
        port: 8081
      service:
        - name: trpc.adp.platform-authenticator.Authenticator
          ip: ${POD_IP}
          port: 9090 # 服务监听端口
          network: tcp # 网络监听类型 tcp/udp
          protocol: trpc # 应用层协议 trpc/restful
          timeout: 3000 # 请求最长处理时间，单位毫秒
    plugins: #插件配置
      log: #日志配置
        default: #默认日志的配置，可支持多输出
          - writer: console
            level: error
          - writer: file # 本地文件日志
            level: debug # 标准输出日志的级别，开发提测环境可以用debug，线上建议用info
            writer_config: # 本地文件输出具体配置
              filename: /app/log/trpc.log # 本地文件滚动日志存放的路径
              max_size: 100 # 本地文件滚动日志大小，单位 MB
              max_backups: 10 # 最大日志文件数
              max_age: 7 # 最大日志保留天数
              compress: false # 日志文件是否压缩
      telemetry:
        opentelemetry:
          addr: {{ ((.Values.global.observability).apm).otlp | default "" }}
          tenant_id: adp
          sampler:
            fraction: 1
          traces:
            disable_trace_body: false
          metrics:
            {{- if ((.Values.global.observability).apm).registry }}
            registry_endpoints: ["{{ .Values.global.observability.apm.registry}}"]
            {{- end }}
          logs:
            enabled: true
            level: "debug"
            trace_log_mode: "disable"
          {{- if ((.Values.global.observability).apm).attributes }}
          attributes:
            {{- range $key, $value := .Values.global.observability.apm.attributes }}
          - key: {{ $key }}
            value: {{ $value }}
            {{- end }}
          {{- end }}
      config:
        file:
          providers:
            - name: rainbow
              path: /app/conf/
            - name: global
              appid: ${RAINBOW_APP_ID}  # appid
              group: global # 配置所属组
              type: kv   # 七彩石数据格式, kv(默认), table
              env_name: ${RAINBOW_ENV_NAME}
              timeout: 2000
              enable_client_provider: true
      i18n:
        i18n-adp:
          default_lang: zh-CN
          supported_languages:
            - zh-CN
            - en-US
          data_provider:
            type: rainbow
            prefix: platform-authenticator
            error_prefix: error
            char_scaling_factor:
              zh: 1
              en: 3

    client:                                            #客户端调用的后端配置
      filter:                                          #针对所有后端调用函数前后的拦截器列表
        - cle-route-propagator
        - opentelemetry
      namespace: ${NAMESPACE}                          #针对所有后端的环境
      timeout: 3000                                    #针对所有后端的请求最长处理时间
      service:                                         #针对单个后端的配置，默认都有默认值，可以完全不用配置
        - name: tdsql.adp.permission
          target: dsn://${INFRA_MIDDLEWARES_DB_0_USER}:${INFRA_MIDDLEWARES_DB_0_PASSWORD}@tcp(${INFRA_MIDDLEWARES_DB_0_HOST}:${INFRA_MIDDLEWARES_DB_0_PORT})/openplatform_permission_data?charset=utf8mb4&timeout=1s&parseTime=true&interpolateParams=true&loc=Local
        - name: redis.authenticator
          target: redis://:${INFRA_MIDDLEWARES_REDIS_0_PASSWORD}@${INFRA_MIDDLEWARES_REDIS_0_HOSTS}:6379
          timeout: 800
        - name: ti-auth-account-http
          target: dns://ti-perm-auth.{{ .Release.Namespace }}.svc.cluster.local:8081
          network: tcp
          protocol: http
          timeout: 10000
