images:
  adp-resource-gallery:
    url: "{{ .Values.global.imageRegistry }}/tke-market/resource-gallery:33_2609161633_stable_iaas_v4.0.3.0_595a0e1a_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
experience_center_uin: '999999999'
replicas: 1
