images:
  adp-resource-gallery:
    url: "{{ .Values.global.imageRegistry }}/tke-market/resource-gallery:30_2607271703_stable_iaas_v4.0.3.0_25fe3dcf_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
experience_center_uin: '999999999'
replicas: 1
