images:
  adp-platform-content-moderation:
    url: ccr.ccs.tencentyun.com/tke-market/bot-infosec-server:17_2605071117_stable_v3.4.1.1_1dad608f_private
resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: "1"
    memory: 2Gi
replicas: 1
