kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-plugin-pod-schedule
  namespace: {{ .Release.Namespace }}
data:
  error_en-US.json: |
    {
      "Pod配置不存在": "Pod configuration does not exist",
      "KubeConfig初始化失败": "Failed to initialize KubeConfig",
      "Pod资源加锁失败，请稍后重试": "Failed to lock Pod resource, please try again later",
      "Pod资源暂无可用，请稍后重试": "No available Pod resources, please try again later",
      "请求参数不合法": "Invalid request parameters",
      "没有已调度的Pod": "No scheduled Pods",
      "账号Pod达到上限": "Account Pod limit reached"
    }
  error_en.json: |
    {
      "Pod配置不存在": "Pod configuration does not exist",
      "KubeConfig初始化失败": "Failed to initialize KubeConfig",
      "Pod资源加锁失败，请稍后重试": "Failed to lock Pod resource, please try again later",
      "Pod资源暂无可用，请稍后重试": "No available Pod resources, please try again later",
      "请求参数不合法": "Invalid request parameters",
      "没有已调度的Pod": "No scheduled Pods",
      "账号Pod达到上限": "Account Pod limit reached"
    }

  error_zh-CN.json: |
    {
      "Pod配置不存在": "Pod配置不存在",
      "KubeConfig初始化失败": "KubeConfig初始化失败",
      "Pod资源加锁失败，请稍后重试": "Pod资源加锁失败，请稍后重试",
      "Pod资源暂无可用，请稍后重试": "Pod资源暂无可用，请稍后重试",
      "请求参数不合法": "请求参数不合法",
      "没有已调度的Pod": "没有已调度的Pod",
      "账号Pod达到上限": "账号Pod达到上限"
    }
  error_zh.json: |
    {
      "Pod配置不存在": "Pod配置不存在",
      "KubeConfig初始化失败": "KubeConfig初始化失败",
      "Pod资源加锁失败，请稍后重试": "Pod资源加锁失败，请稍后重试",
      "Pod资源暂无可用，请稍后重试": "Pod资源暂无可用，请稍后重试",
      "请求参数不合法": "请求参数不合法",
      "没有已调度的Pod": "没有已调度的Pod",
      "账号Pod达到上限": "账号Pod达到上限"
    }

  kube.yaml: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1EY3hOVEUxTVRZMU5sb1hEVE0xTURjeE16RTFNVFkxTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS240CjdBek9CSWpZb3J0YWM4dFIzV1lZa1ZSUUZGWWtSNmpyNUVVUElrUzU3Z2R0QmFZcTg4bDFXWG9EaEMvR0VZTEQKdy9tTzVQNE42Y2JFRFF2SjhxZ29TSE9IZWI2MnlxVkdFd1hRaGJSVWhuR2R0UVJGRWlTUkkrRVg3NCtDcFZCUApsek0rQ2JldWJzNkE3QTlBRDJjc3lKRWRnaWpqMVYycHYrOGY1bHVOYlRrUGJtQ2F6aGJxSi9mNGNHQ0svditCCjZMVkRYNHBaTENraTFoakVyTFlFTnBoRXVpYk1uTjlBUzdNL0FHV3Yza1lud3lVQXZ3VklNWUFnWU5WODkxdUEKd2oyM09vQUlTNU1XMkJmOE5Bek5pVXJuam05a0xGOXFRZGVSdDM3LzRlVkJRZjlmY1JBNkFyVUhRTjdDajA4QwpORE9wSGpCWTFNbXBGYkZ1ZFI4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0tVTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJT0VsK293eXJCVlhhSTVQRzUxK2t3QmN3VmwKSU9wSGkzYVlnU2VzaXNtV2dFZjAvUDNtY0xrOVFaRFJ5YUtpNFhRcGQyRjhkNzNQRHF0bGxZT1BhV1dUUFpvRgpFeENscTJsOFlZVnVSTFkrUnlUejVHRjRhSWhyd2QwNmhHN1gzRHZMeTRZdks1b3BsODNPb0FOcU1PQTlZMkJrCkZENjV0aWtCZVpLQ3NUU0xiODdEdzNoTkI1WEx5UnN2clZZdG9NUlduaGFINWpDQWdERjkzaktLTUUwV2RZWnMKRGVpc3R2NUFKTCs0dUUyeVZOOElLRjY2VmJKeEYxTk9kaFhDdnNEWHFLVW96SWFuL0tIT2crTE5WZHFHa3hXdApnT2NBWjBZTldidkR5d0dmWS9iNTZvaS83L0trY05hak1MN2w0TmNKMUNPQlJKNXJGR1ZmWURybVEzVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        server: https://21.57.232.62
      name: cls-js1gvtg7
    contexts:
    - context:
        cluster: cls-js1gvtg7
        user: "100040432464"
      name: cls-js1gvtg7-100040432464-context-default
    current-context: cls-js1gvtg7-100040432464-context-default
    kind: Config
    preferences: {}
    users:
    - name: "100040432464"
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lJT0NRa1hBZi9oOEl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBM01UVXhOVFF6TVRSYUZ3MDBOVEEzTVRVeE5UUXpNVFJhTURZeApFakFRQmdOVkJBb1RDWFJyWlRwMWMyVnljekVnTUI0R0ExVUVBeE1YTVRBd01EUXdORE15TkRZMExURTNOVEkxCk9UUXhPVFF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREJoc25Ib3d6TStmMC8KNU1zV2hOQS9HdmtmODFuQVBzQ2tZeFJObC9tNFNkYVV6ZHI3VWhZNWV3NUNVUEdnRmIzbEh1dlh5eHZTWmx2TwpBZnpSd1hlNHVwZmRUUXlySWtOYkFvc3NVRmtxVVpwZEJob0xxMEQwS1VrYVNiT09vb04xTDRaaVVtUHpnNnFECjNzbzZ2bjZ6QnZETFYxNHR4RDZyOTN4UFNLa0FWTjdOeGxYUTdXZUYxYUo5em0vOUNUVytDUjg2bkZjV3kybE8Kb2pFTXhyd3RJYVYwbml6Q3BtMUtIRElxem1JN2kzQmYzajczZEpBazI0STJGSm9SeExsMjVXZFo0REJmeUZOaQpPOVJLSk1pQjZZVno4dUxRUnZPTGoxcThrYlNtV1F3RUtoSHdGK3AyWlJTS0dtblQ3aVNyREJEdG0vWjNyWkRYCktLajRLamdYQWdNQkFBR2pQekE5TUE0R0ExVWREd0VCL3dRRUF3SUNoREFkQmdOVkhTVUVGakFVQmdnckJnRUYKQlFjREFnWUlLd1lCQlFVSEF3RXdEQVlEVlIwVEFRSC9CQUl3QURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpQaVdaTHFpSDF5NjdYaU9PNmEySEpsdTdtL0RhdEl4QUx6QWNiMFViMUtxcXZ3U2hRMllwV2hsciswMDNRNTI1CkNvVWh6Rm9jU29Ua0VLVHFhOHA3OXlVVzQyN2NvY0hWbTlxVkMyMFA0SHlrOGpVSy9zK3k3UnU4cG5SVmt5T2EKaFBycGc3dkhqR2U4VFhoVUFpVi91cXdTcytRbkk2VEQ2eTRtZjRla21VN1BQcllvTnM2UTA1VUlWa3NibVFDSwpmK0VNSXowSkMxaXVpdlVBazRSMlZycm9aQVJPWDJhNnRMVVF5aE1GVXBtcHhFYzMzV3hKMUxldko2Mm1iRXBGCjNzN3Z6ZDYyOEpBQ05FdERXampHRkF3b2xnRzc4N0tDd0VxTWJhUlJRSDBQTmV2WkNjUWh1Tk01d3NGaEcyeW0KbUozVTdGbVJHaytDOXhJR2w1WGxvUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBd1liSng2TU16UG45UCtUTEZvVFFQeHI1SC9OWndEN0FwR01VVFpmNXVFbldsTTNhCisxSVdPWHNPUWxEeG9CVzk1UjdyMThzYjBtWmJ6Z0g4MGNGM3VMcVgzVTBNcXlKRFd3S0xMRkJaS2xHYVhRWWEKQzZ0QTlDbEpHa216anFLRGRTK0dZbEpqODRPcWc5N0tPcjUrc3did3kxZGVMY1ErcS9kOFQwaXBBRlRlemNaVgowTzFuaGRXaWZjNXYvUWsxdmdrZk9weFhGc3RwVHFJeERNYThMU0dsZEo0c3dxWnRTaHd5S3M1aU80dHdYOTQrCjkzU1FKTnVDTmhTYUVjUzVkdVZuV2VBd1g4aFRZanZVU2lUSWdlbUZjL0xpMEViemk0OWF2SkcwcGxrTUJDb1IKOEJmcWRtVVVpaHBwMCs0a3F3d1E3WnYyZDYyUTF5aW8rQ280RndJREFRQUJBb0lCQVFDSTNOWWV4WVRzQVcvRQptLzIwYzBFRElBUkhRRWFjMnNSS2ZYZUNXSlJXYklIQXdzUzNNQnBmbEZORk94Rm1jWG5XYThQRzNQRlVIdWVXCkRYbktyZFFKWkl5NkNSK0lkN2JDeWsyNmpTaEI4V3dGbGFjZDBZTWlLWUIxZ3VIbFliRXVVdW5xNXZHZzZlRFIKV2VJVElWMWhKdXRzSXVHTDVGbWVMR3hSZGNWdllWcFVPVVBvNWxWU0FsRCtYYldCSUl2c09CU2xFNVBYRkJXWgorQTkvUThnQUpYaXNnWXFSaVZrekl0MHpXMkNGc2w0RjZmUEZEczI0TTNCYnYvZ09SRzdxcWJ0a0laUEo1TUlVCjZjekV0RmhVS1V2VkNkc2VwQk95TzVxQUQrT2VvdFhvcFE5YkdqYnkvdHhTTkZXSjU3S3d3QlBiUlo1T01iYkIKKzE3akJpaWhBb0dCQVBERllicXZSbFZJUjdvSTk3WU1OSVJROGtsRFFsaE94bVdWWkdTUXZCajlrMTQzWGtNdApNbVR4MVpZbkVlY3ptaU4ybVlXYUZDTzlSQ0NIMXoyaEVIamllb2tvVFlKSWJKZkNqdmNBcmRnbC9aUW5vRjBwClI5MWhhSFpMb1FyZHQ3cEo4bm9obUNMN2J1cHRaaFR6U2dreTNXQ2o1U1o2a1JhZGtBaXBSUTlkQW9HQkFNM0UKYWEvU1FlbjJNWS9RQnRqZzNpcGM2cVRCMFRVNlNldk9qWHVVdnc4UjRES0JJYVl1VWZpVzNmTVloZlExak5lQQo2NEFVeU5oY0wwQXc1bklKR3BzZjlUVWZSaVhYbDhMK2FlN25hQkJxRFhzYkhEeW00L0ZNc0RObjcwdVA1dWxXCllaMkJoQk4vaG1WbjRzQjcwZzhZTVNNK3hRS1A4aTlPalNlZWVKSURBb0dCQUpJTmVmSXYzcjlmQUR1bXN2VVkKeEVhN2Y2M1hnZ2hsaU00WWFIVGtvMldaZE9yRE5ZZ1VnNnhlVXMwcDJCOWkydzdHSSt5Nmdac0lkYW95SE94QwpwdVpkcEMxTmFHOHVsY2tkZVhIMlZINTQxVEVwTklzdXZteFphVy9SQXRpL2xITUo1bkFWcnQ4Um5ML1NLd2xzClo2M2EwQldPZGpQNFI4anJQWE16a3pQMUFvR0FOZzJpdGMxR0EyL3BGUjVRcmloa05EeTBaeE9ESWJodU1zUFAKNXVic1Nja29YQndQK3Rld01OMXc4S3RBaFNhTUdSQ0V6T0NvNGkxVlBFZWNRZGlpWkozQWpIUHF1WVlwRjlBOQpnOFRHVVltS2dReGVIcEM0MEdxVTN1d3VzR3JjL2U3ek5hMFFSUTc2L3lpTEtJVmVhUml4ejlCdGNIN2Y0QTJDCmh5WGFCb0VDZ1lFQWhNa1FBTGFFbWVmNjUxeGhRWExUcHpCSkRSZWQ0RjY2SGI2bmdsc3ZBSy9HVzNHeUNGWm8KR0x2eTFSYXZBQkpmeXFlc3plejRPd2kwSXBiVXZoRTlueVV4eUNSY0thc3pYa2lSYml6R3VlVW8ycnROZUZsOApNV29ST3VCNzcrT0F2Zmcxd2dub1hiMlpSalB5eTVWb3JtY2FtV0lTVzQ5NmF3NHE3ZkE2UTJzPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  main.yaml: |
    redis_lock:
      wait_time: 60
      expire_time: 60
      lock_key: pod_lock_key
      lock_value: apply_pod

    pod_schedule:
      real_time: false
      max_try_count: 3
      try_wait_time: 5ms

      limit_uin_max_pod: true
      default_uin_max_pod: 20
      uin_limit_whitelist:
        "700000576145": 8 # 测试

    pod_info:
      type: lb
      namespace: {{ .Release.Namespace }}
      service_name: mcp-sandbox

      max_pods: 20      # 最大数量
      min_pods: 10       # 最小数量
      upper_thr: 0.8    # 扩容阈值
      lower_thr: 0.3    # 缩容阈值

      expired_time: 600 # 过期时间（单位：s）

      server_config:
        1: # 沙箱MCP
          port: 8000
          url_format: "http://%s:%d/runtime_mcp/sse"
        2: # 沙箱VNC
          port: 8080
          url_format: "http://%s:%d/vnc_lite.html"
        3: # 沙箱CODE
          port: 9000
          url_format: "http://%s:%d/execute"

  placeholder.yaml: |
    REDIS_TARGET: 

    # main.yaml

    # pod??????
    POD_SCHEDULE:
      real_time: false
      max_try_count: 3
      try_wait_time: 5ms

      limit_uin_max_pod: true
      default_uin_max_pod: 4
      uin_limit_whitelist:
        100024239198: 5 # halelv
        100034812856: 20 # hank
        100034812935: 20 # hank

    # pod????
    POD_INFO:
      type: lb
      namespace: mcp-sandbox
      service_name: bot-mcp-sandbox
      max_pods: 100
      min_pods: 50
      upper_thr: 0.8
      lower_thr: 0.3
      expired_time: 600
      server_config:
        1:
          port: 8000
          url_format: "http://%s:%d/runtime_mcp/sse"
        2:
          port: 8080
          url_format: "http://%s:%d/vnc_lite.html"
        3:
          port: 9000
          url_format: "http://%s:%d/execute"

    # client.yaml

  trpc_go.yaml: |
    global:                                   #全局配置
      namespace: Development                  #环境类型，分正式production和非正式development两种类型
      env_name: dev                           #环境名称，非正式环境下多环境的名称
      enable_set: false               #是否启用set
      full_set_name: adp         #set名
      local_ip: ${POD_IP}
      container_name: ${POD_NAME}
    server:                                   #服务端配置
      app: adp                                #业务的应用名
      server: plugin-pod-schedule             #进程服务名
      bin_path: /app/bin/                     #二进制可执行文件和框架配置文件所在路径
      conf_path: /app/conf/                   #业务配置文件所在路径
      data_path: /app/data/                   #业务数据文件所在路径
      filter:                                 #针对所有service处理函数前后的拦截器列表
        - recovery                            #拦截框架创建的业务处理协程panic
      admin:
        ip: ${POD_IP}                         # admin 的 ip，配置网卡 nic 也可以
        port: 8081                            # admin 的 port，必须同时配置这里的 ip port 才会启动 admin
      service:                                #业务服务提供的service，可以有多个
        - name: trpc.KEP.resource-schedule-server.ScheduleServer  #service的路由名称
          ip: ${POD_IP}                       #服务监听ip地址 可使用占位符 ${ip},ip和nic二选一，优先ip
          port: 8000                          #服务监听端口 可使用占位符 ${port}
          network: tcp                        #网络监听类型  tcp udp
          protocol: trpc                      #应用层协议 trpc http
          timeout: 0                          #请求最长处理时间 单位 毫秒
          server_async: true                  #开启异步处理
          idletime: 600000                    # idletime，设置tcp空闲等待时间，避免耗时过长的操作导致trpc-go将tcp关闭
        - name: trpc.KEP.resource-schedule-server.syncNodes  # service 的路由名称
          ip: ${POD_IP}
          port: 9090                          # 服务监听端口 可使用占位符 ${port}
          network: "* 0/1 * * * ?startAtOnce=1&scheduler=syncNodes"  # 任务调度策略
          protocol: timer                     # 设置服务类型为定时器服务
          timeout: 10000
    plugins:                                  #插件配置
      log:                                    #日志配置
        default:                              #默认日志的配置，可支持多输出
          - writer: console                   #控制台标准输出 默认
            level: debug                      #标准输出日志的级别
          - writer: file                      # 本地文件日志
            level: debug                      # 标准输出日志的级别，开发提测环境可以用debug，线上建议用info
            writer_config:                    # 本地文件输出具体配置
              filename: /app/logs/trpc.log    # 本地文件滚动日志存放的路径
              max_size: 200                   # 本地文件滚动日志大小，单位 MB
              max_backups: 10                 # 最大日志文件数
              max_age: 7                      # 最大日志保留天数
              compress: false                 # 日志文件是否压缩
      config:
        file:
          providers:
            - name: rainbow
              path: /app/conf/
            - name: global
              appid: ${RAINBOW_APP_ID}        # appid
              group: global                   # 配置所属组
              type: kv                        # 七彩石数据格式, kv(默认), table
              env_name: ${RAINBOW_ENV_NAME}
              timeout: 2000
              enable_client_provider: true
      registry:                               #服务注册配置
        polaris:                              #北极星名字注册服务的配置
      i18n:
        i18n:
          default_lang: zh
          data_provider:
            type: rainbow
            prefix: resource-schedule
            error_prefix: error
      selector:                               #针对用户自定义的selector的配置
        polaris:                              #针对polaris整体api的内部配置
          protocol: grpc                      #名字服务远程交互协议类型
    client:                                   #客户端调用的后端配置
      namespace: Production                  #针对所有后端的环境
      stream_filter:
      service:
        - name: redis.resource-schedule-server
          network: tcp
          target: ip://${INFRA_MIDDLEWARES_REDIS_0_HOSTS}:6379/2
          password: ${INFRA_MIDDLEWARES_REDIS_0_PASSWORD}
          timeout: 800
