images:
  adp-crawler:
    url: "{{ .Values.global.imageRegistry }}/tke-market/webappchatbot:crawl-stable_iaas_v4.0.3.0-5a93e75-170"
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 1
    memory: 2Gi
tad:
  components:
    adp-crawler:
      replicas: 1
      type: Deployment

  type: helm
  instanceStrategy:
    level: region
  labels: {}
  product: llm-knowledge-engine
  services: {}

