apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ti.cloud.tencent.com/resource-quota: unlimited
    configmap.reloader.stakater.com/reload: {{ .Release.Name }}-private-op
    {{- if .Values.global.customAnnotations }}
    {{- range $key, $value := .Values.global.customAnnotations }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
  labels:
    app: adp-private-op
    app.kubernetes.io/name: adp-private-op
    {{- if .Values.global.customLabels }}
    {{- range $key, $value := .Values.global.customLabels }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
  name: adp-private-op
  namespace: {{ .Release.Namespace }}
spec:
  # op无需高可用
  {{- if eq .Values.global.clusterSize "minimal" }}
  replicas: 1
  {{- else if eq .Values.global.clusterSize "standard" }}
  replicas: 1
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: adp-private-op
  strategy : {}
  template:
    metadata:
      labels:
        app: adp-private-op
        {{- if .Values.global.customLabels }}
        {{- range $key, $value := .Values.global.customLabels }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
        {{- end }}
      {{- if .Values.global.customAnnotations }}
      annotations:
        {{- range $key, $value := .Values.global.customAnnotations }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
      {{- end }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - private-op
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: GPUName
                    operator: DoesNotExist
            - weight: 50
              preference:
                matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - lke
      serviceAccountName: adp-private-op-controllers
      priorityClassName: system-cluster-critical
      {{- if eq (include "needInitContainer" .) "true" }}
      serviceAccountName: adp-reader
      {{- end }}
      initContainers:
        {{- include "dependencyChecker.initContainer" . | nindent 8 }}
      containers:
        - env:
            - name: MKL_NUM_THREADS
              value: "2"
            - name: LOG_SPACES
              value: "2097152"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DEPLOYMENT_ENVIRONMENT
              value: TCS
            - name: NAME_SPACE
              value: default
            - name: ENV
              value: tcs
            - name: SERVER_LOG_LEVEL
              value: info
            # - name: LOKI_BASE_URL
            #   value: http://otel-clickhouse-apiserver.opentelemetry.svc.cluster.local:3100
            - name: APISIX_BASE_URL
              value: "{{ .Values.global.scheme }}://{{ .Values.global.clb }}/apisix/admin"
            - name: APISIX_API_KEY
              value: "2bffd108f0a56053e665440292bc529a"
            - name: TI_AUTH_PROXY_BASE_URL
              value: http://ti-perm-auth-proxy.ti-base.svc.cluster.local:80
          image: {{ include "resolveImageUrl" (dict "url" (index .Values.images "adp-private-op").url "context" .) }}
          imagePullPolicy: Always
          command: ["/app/bin/private-op", "-conf", "/app/conf/trpc_go.yaml"]
          name: adp-private-op
          {{- $adp_private_op := index (index .Values.components "adp-private-op").resources "adp-private-op" }}
          {{- if eq .Values.global.clusterSize "minimal" }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "125m"
              memory: "512Mi"
          {{- else if eq .Values.global.clusterSize "standard" }}
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "512Mi"
          {{- else }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /app/logs
              name: logdata
              subPathExpr: $(POD_NAME)
            - mountPath: /app/conf/trpc_go.yaml
              name: config
              subPath: trpc_go.yaml
      imagePullSecrets:
        - name: qcloudregistrykey
        - name: lmbkeregistrykey
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        {{- include "dependencyChecker.volumes" . | nindent 8 }}
        - hostPath:
            path: /etc/localtime
          name: localtime
        - hostPath:
            path: /data/ti-platform/log/private-op
            type: DirectoryOrCreate
          name: logdata
        - configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-private-op
          name: config
