apiVersion: v1
kind: Service
metadata:
  labels:
    app: adp-private-op
  name: adp-private-op
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: adp-private-op
  sessionAffinity: None
  type: ClusterIP
