images:
  adp-file-converter:
    url: "{{ .Values.global.imageRegistry }}/tke-market/webappchatbot:fileconvertor-a6b5291-74"
  adp-file-converter-sidecar:
    url: "{{ .Values.global.imageRegistry }}/tke-market/webappchatbot:fileconvertor-sidercar-41745c1-80"
replicas: 1
