images:
  adp-file-converter:
    url: "{{ .Values.global.imageRegistry }}/tke-market/webappchatbot:fileconvertor-450bec0-15"
  adp-file-converter-sidecar:
    url: "{{ .Values.global.imageRegistry }}/tke-market/webappchatbot:fileconvertor-sidercar-450bec0-15"
replicas: 1
