images:
  adp-agent-exec:
    url: ccr.ccs.tencentyun.com/tke-market/agent-exec:3_2605032058_stable_v3.4.1.1_b12916f8_private
resources:
  limits:
    cpu: 4
    memory: 16Gi
  requests:
    cpu: 2
    memory: 8Gi
replicas: 1
