kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-app-memory
  namespace: {{ .Release.Namespace }}
data:
  error_en-US.json: |
    {
        "用户未登录": "User not logged in",
        "意图不存在": "Intent does not exist"
    }

  error_zh-CN.json: |
    {
        "用户未登录": "用户未登录",
        "意图不存在": "意图不存在"
    }

  main.yaml: |
    memory_prompt: |
      你是一个用户画像总结助手，需要根据<默认提取规则>，从用户输入中总结出用户画像。当<用户自定义提取规则>不为空时，优先遵循<用户自定义提取规则>。

      <默认提取规则>
      用户画像包括以下信息: 
      (1) 用户个人信息，如姓名、年龄、性别、爱好、性格特征等；
      (2) 用户已经发生的一些关键事件。

      用户画像不包含以下内容：
      (1) 时效性较强的内容："北京明天下雨吗？"、"今天股市收盘指数是多少？"、"湖人队比分是多少？"
      (2) 闲聊内容："今天路上好堵啊"、"帮我讲个笑话吧"
      (3) 未发生的事务："帮我查一下后天飞上海的机票"、"帮我预定下午3点的会议室"、"后天小张约我去爬山，你推荐我准备哪些装备？"
      </默认提取规则>


      <提取示例>
      示例1:
      用户输入: 你好呀，我叫Owen
      对应的模型输出: {"是否包含用户画像": "是", "用户画像": "名字叫Owen"}

      示例2: 
      用户输入: 每天都跑步。此外，我喜欢玩水，我从小就会游泳
      对应的模型输出: {"是否包含用户画像": "是", "用户画像": "喜欢跑步和游泳"}

      示例3: 
      用户输入: 明天的天气怎么样
      对应的模型输出: {"是否包含用户画像": "否", "用户画像": ""}

      示例4: 
      用户输入: 我家冰箱已经空了
      对应的模型输出: {"是否包含用户画像": "否", "用户画像": ""}
      </提取示例>


      <用户自定义提取规则>
      {自定义长期记忆提示词}
      </用户自定义提取规则>


      现在开始你的任务。判断<用户输入>是否包含用户画像。如果包含的话，将用户画像总结为一句话。用户画像应该简洁，只包含用户个人信息和已经发生关键事事件。如果提取到的用户画像和<已收集到的用户画像>内容重复，不要再次提取。

      <已收集到的用户画像>
      {历史用户画像}
      </已收集到的用户画像>

      <用户输入>
      用户输入: %s
      </用户输入>

      用以下JSON格式输出:
      {
      "是否包含用户画像": "是 或者 否",
      "用户画像": "用一句话总结用户画像。如果<用户输入>中不包含用户画像，则置空"
      }

      - 只有用户个人信息和已经发生的关键事件，是可以记录的，其他信息都不可以总结为用户画像
      - 严格遵守<用户自定义提取规则>中的要求
      - <用户输入>是疑问句，没有明确表达个人画像，不要提取用户画像
      - 提取到的用户画像和<已收集到的用户画像>内容重复，不要再次提取

    llm: 
      model_name: "lke-deepseek-v3-0324"
    memory_content_max_length: 140
    infosec:
      disable_content_check: true

    long_term_memory_max_count: 50 
    app_var_expire_time: 168
    long_term_memory_worker_count: 100
    long_term_memory_scan_batch_size: 1000

    finance:
      model_config:
        # TCADP/glm-5:
        #   default_qpm: 10
        #   default_tpm: 20000
        # TCADP/kimi-k2.5:
        #   default_qpm: 10
        #   default_tpm: 20000
        # TCADP/minimax-m2.5:
        #   default_qpm: 10
        #   default_tpm: 20000
  memory_en-US.json: |
    {}

  memory_zh-CN.json: |
    {}

  placeholder.yaml: |

    AI_GATEWAY_TARGET: ip://adp-ai-gateway.{{ .Release.Namespace }}.svc.cluster.local:9090
    ADMIN_LOGIN_TARGET: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9091
    ADMIN_API_TARGET: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9092
    INFOSEC_TARGET: ip://adp-platform-content-moderation.{{ .Release.Namespace }}.svc.cluster.local:9090
    MEMORY_TARGET: ip://adp-app-memory.{{ .Release.Namespace }}.svc.cluster.local:8001
    FINANCE_TARGET: ip://adp-platform-charger.{{ .Release.Namespace }}.svc.cluster.local:9090
    PLATFORM_METROLOGY_TARGET: ip://adp-platform-metrology.{{ .Release.Namespace }}.svc.cluster.local:8000
    PLATFORM_LOGIN_TARGET: ip://adp-platform-manager.{{ .Release.Namespace }}.svc.cluster.local:9091
    RESOURCE_GALLERY_ADMIN_TARGET: ip://adp-resource-gallery.{{ .Release.Namespace }}.svc.cluster.local:9090
    APP_CONFIG_ADMIN_TARGET: ip://adp-app-config.{{ .Release.Namespace }}.svc.cluster.local:9090

  trpc_go.yaml: |
    global:
      namespace: Production
    server:
      app: adp
      server: app-memory
      bin_path: /app/bin/
      conf_path: /app/conf/
      log_path: /app/logs/
      admin:
        ip: ${POD_IP}
        port: 8081
        read_timeout: 3000
        write_timeout: 60000
      filter:
        - recovery
        - i18n-adp
        - debuglog
        - cle-route-propagator
        - opentelemetry
      service:
        - name: trpc.KEP.bot-memory-server.memory
          ip: ${POD_IP}
          port: 8000
          network: tcp
          protocol: trpc
          server_async: true
          idletime: 600000
          filter:
            - session
            - permission
        - name: trpc.KEP.bot-memory-server.memoryInner
          ip: ${POD_IP}
          port: 8001
          network: tcp
          protocol: trpc
          server_async: true
          idletime: 600000
        - name: trpc.KEP.bot-memory-server.longTermMemoryReport
          ip: ${POD_IP}
          port: 9001
          network: "0 */13 * * * * ?scheduler=distributed&startAtOnce=1"
          protocol: timer
          timeout: 3500000
    client:
      filter:
        - cle-route-propagator
        - debuglog
        - opentelemetry
      service:
        - name: trpc.tcadp.memory.redis
          target: redis://:${INFRA_MIDDLEWARES_REDIS_0_PASSWORD}@${INFRA_MIDDLEWARES_REDIS_0_HOSTS}:6379
        - name: redis.lke.limiter
          network: tcp
          protocol: redis
          target: ip://${INFRA_MIDDLEWARES_REDIS_0_HOSTS}:6379/4
          password: ${INFRA_MIDDLEWARES_REDIS_0_PASSWORD}
          timeout: 800
        - name: trpc.tcadp.memory.tdsql
          target: dsn://${INFRA_MIDDLEWARES_DB_0_USER}:${INFRA_MIDDLEWARES_DB_0_PASSWORD}@tcp(${INFRA_MIDDLEWARES_DB_0_HOST}:${INFRA_MIDDLEWARES_DB_0_PORT})/db_llm_robot?charset=utf8mb4&timeout=1s&parseTime=true&interpolateParams=true&loc=Local
        - name: trpc.tcadp.memory.mysql
          target: dsn://${INFRA_MIDDLEWARES_DB_0_USER}:${INFRA_MIDDLEWARES_DB_0_PASSWORD}@tcp(${INFRA_MIDDLEWARES_DB_0_HOST}:${INFRA_MIDDLEWARES_DB_0_PORT})/db_llm_robot?charset=utf8mb4&timeout=1s&parseTime=true&interpolateParams=true&loc=Local
        - name: trpc.adp.ai-gateway.api
          namespace: Production
          network: tcp
          protocol: http
          target: ip://adp-ai-gateway.{{ .Release.Namespace }}.svc.cluster.local:9090
          timeout: 1800000
        - callee: trpc.adp.app_admin_proxy.Login
          namespace: Production
          target: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9091
          protocol: trpc
          timeout: 20000
        - callee: trpc.adp.app_admin_proxy.Api
          namespace: Production
          target: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9092
          protocol: trpc
          timeout: 20000
        - callee: trpc.adp.platform_content_moderation.Infosec
          namespace: Production
          target: ip://adp-platform-content-moderation.{{ .Release.Namespace }}.svc.cluster.local:9090
          network: tcp
          timeout: 500
        - callee: trpc.KEP.bot_admin_config_server.Login
          namespace: Production
          target: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9091
          protocol: trpc
          timeout: 20000
        - callee: trpc.KEP.bot_admin_config_server.Api
          namespace: Production
          target: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9092
          protocol: trpc
          timeout: 20000
        - callee: trpc.adp.platform_manager.Login
          namespace: Production
          target: ip://adp-platform-manager.{{ .Release.Namespace }}.svc.cluster.local:9091
          protocol: trpc
          timeout: 6000
        - callee: trpc.adp.platform_metrology.Api
          namespace: Production
          target: ip://adp-platform-metrology.{{ .Release.Namespace }}.svc.cluster.local:8000
          protocol: trpc
          timeout: 20000
        - callee: trpc.KEP.bot-data-statistics-server.Api
          namespace: Production
          target: ip://adp-platform-metrology.{{ .Release.Namespace }}.svc.cluster.local:8000
          protocol: trpc
          timeout: 20000
        - callee: trpc.adp.platform_charger.Api
          name: qbot.finance.finance.Finance
          target: ip://adp-platform-charger.{{ .Release.Namespace }}.svc.cluster.local:9090
          namespace: Production
          network: tcp
          timeout: 300000
        - callee: trpc.adp.app_memory.MemoryInner
          name: trpc.KEP.bot-memory-server.memoryInner
          namespace: Production
          target: ip://adp-app-memory.{{ .Release.Namespace }}.svc.cluster.local:8001
          protocol: trpc
          timeout: 20000
        - callee: trpc.KEP.bot_memory_server.MemoryInner
          name: trpc.KEP.bot-memory-server.memoryInner
          namespace: Production
          target: ip://adp-app-memory.{{ .Release.Namespace }}.svc.cluster.local:8001
          protocol: trpc
          timeout: 20000
        - callee: trpc.adp.platform_charger.Finance
          target: ip://adp-platform-charger.{{ .Release.Namespace }}.svc.cluster.local:9090
          namespace: Production
          network: tcp
          timeout: 30000
        - callee: trpc.adp.resource_gallery.Admin
          target: ip://adp-resource-gallery.{{ .Release.Namespace }}.svc.cluster.local:9090
          namespace: Production
          protocol: trpc
          timeout: 20000
        - callee: trpc.adp.app_config.Admin
          target: ip://adp-app-config.{{ .Release.Namespace }}.svc.cluster.local:9090
          namespace: Production
          protocol: trpc
          timeout: 30000
    plugins:
      telemetry:
        opentelemetry:
          addr: {{ ((.Values.global.observability).apm).otlp | default "" }}
          tenant_id: adp
          sampler:
            fraction: 1
          traces:
            disable_trace_body: false
          metrics:
            {{- if ((.Values.global.observability).apm).registry }}
            registry_endpoints: ["{{ .Values.global.observability.apm.registry}}"]
            {{- end }}
          logs:
            enabled: true
            level: "debug"
            trace_log_mode: "disable"
          {{- if ((.Values.global.observability).apm).attributes }}
          attributes:
            {{- range $key, $value := .Values.global.observability.apm.attributes }}
          - key: {{ $key }}
            value: {{ $value }}
            {{- end }}
          {{- end }}
      log:
        default:
          - writer: console
            level: error
          - writer: file
            level: debug
            writer_config:
              filename: /app/logs/trpc.log
              max_size: 100
              max_backups: 10
              max_age: 7
              compress: false
      config:
        file:
          providers:
            - name: rainbow
              path: /app/conf/
            - name: global
              appid: ${RAINBOW_APP_ID}  # appid
              group: global # 配置所属组
              type: kv   # 七彩石数据格式, kv(默认), table
              env_name: ${RAINBOW_ENV_NAME}
              timeout: 2000
              enable_client_provider: true
      i18n:
        i18n-adp:
          default_lang: zh-CN
          supported_languages:
            - zh-CN
            - en-US
          data_provider:
            type: rainbow
            prefix: memory
            error_prefix: error
            char_scaling_factor:
              zh-CN: 1
              en-US: 3
      registry:
        polaris:
      selector:
        polaris:
          enable_servicerouter: true
