apiVersion: v1
kind: Service
metadata:
  labels:
    app: adp-model-token-count
  name: adp-model-token-count
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: adp-model-token-count-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: adp-model-token-count-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: adp-model-token-count
  sessionAffinity: None
  type: ClusterIP