images:
  adp-workflow-config:
    url: "{{ .Values.global.imageRegistry }}/tke-market/workflow-config:15_2606151031_stable_iaas_cos_381c1fa2_private"
adp-workflow-config:
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi
replicas: 1
