images:
  adp-workflow-config:
    url: "{{ .Values.global.imageRegistry }}/tke-market/workflow-config:8_2605040928_stable_v3.4.1.1_0b478a79_private"
adp-workflow-config:
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi
replicas: 1
