images:
  adp-kb-retrieval:
    url: "{{ .Values.global.imageRegistry }}/tke-market/kb-retrieval:20_2607151141_stable_iaas_v4.0.3.0_df6c35e2_private"
vector_doc:
  embedding_batch_size: 6
  image_embedding_batch_size: 5
  batch_add_vector_size: 10
  publish:
    embedding_batch_size: 6
    image_embedding_batch_size: 5
    batch_add_vector_size: 10
replicas: 1
