images:
  adp-platform-permission-config:
    url: "{{ .Values.global.imageRegistry }}/tke-market/platform-permission-config:70_2607281936_stable_iaas_v4.0.3.0_55b46479_private"
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 1Gi
replicas: 1
