apiVersion: v1
kind: Service
metadata:
  name: adp-pyright
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ports:
    - name: tcp-30008-30008
      port: 30008
      protocol: TCP
      targetPort: 30008
  selector:
    app: adp-pyright
  type: ClusterIP
