{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.networking.cpaas.io/tls: ""
  name: ti-perm-auth-proxy
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  {{- if eq $.Values.global.scheme "https" }}
  - host: {{ $.Values.global.clb }}
    http:
  {{- else }}
  - http:
  {{- end }}
     paths:
      - backend:
          service:
            name: ti-perm-auth-proxy
            port:
              number: 80
        path: /logout
        pathType: ImplementationSpecific
  {{- if eq $.Values.global.scheme "https" }}
  tls:
  - hosts:
      - {{ $.Values.global.clb }}
    secretName: {{ $.Values.global.clb }}-secret
      {{- end }}
{{- else }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.networking.cpaas.io/tls: ""
    {{- if eq .Values.helmfileEnvName "ksp" }}
    kubernetes.io/ingress.class: apisix
    {{- else }}
    kubernetes.io/ingress.class: ""
    {{- end }}
  name: ti-perm-auth-proxy
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- if eq $.Values.global.scheme "https" }}
  - host: {{ $.Values.global.clb }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - backend:
          serviceName: ti-perm-auth-proxy
          servicePort: 80
        path: /logout
  {{- if eq $.Values.global.scheme "https" }}
  tls:
  - hosts:
      - {{ $.Values.global.clb }}
    secretName: {{ $.Values.global.clb }}-secret
  {{- end }}
  {{- end }}