apiVersion: v1
kind: Secret
metadata:
  name: ti-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.global.components.db.host | quote }}
  DB_PORT: {{ .Values.global.components.db.port | toString | quote }}
  DB_USER: {{ .Values.global.components.db.user | quote }}
  DB_PASSWORD: "{{ .Values.global.components.db.password }}"
