images:
  adp-platform-content-moderation:
    url: "{{ .Values.global.imageRegistry }}/tke-market/bot-infosec-server:35_2607170209_stable_iaas_v4.0.3.0_ee89b62f_private"
resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: "1"
    memory: 2Gi
replicas: 1
