images:
  adp-app-config:
    url: "{{ .Values.global.imageRegistry }}/tke-market/app-config:26_2606132002_stable_iaas_cos_0bc39e23_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
appName: adp-app-config
replicas: 1
