images:
  adp-app-config:
    url: "{{ .Values.global.imageRegistry }}/tke-market/app-config:46_2607271712_stable_iaas_v4.0.3.0_f987d39e_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
appName: adp-app-config
replicas: 1
