images:
  adp-kb-file-manager:
    url: "{{ .Values.global.imageRegistry }}/tke-market/kb-file-manager:38_2607231114_stable_iaas_v4.0.3.0_b20e7112_private"
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi
replicas: 1
