{{- if eq (default $.Values.global.scheme $.Values.global.clbScheme) "https" }}
apiVersion: v1
kind: Secret
metadata:
  name: clb-cert-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  qcloud_cert_id: {{ .Values.global.clbCertId | quote }}
{{- end }}
