apiVersion: v1
kind: Service
metadata:
  labels:
    app: lke-ti-perm-auth-proxy
  name: ti-perm-auth-proxy
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-80-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: lke-ti-perm-auth-proxy
  sessionAffinity: None
  type: ClusterIP