images:
  adp-platform-authenticator:
    url: "{{ .Values.global.imageRegistry }}/tke-market/platform-authenticator:6_2605042043_stable_v3.4.1.1_6eab6539_private"
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 1Gi
replicas: 1
