images:
  adp-platform-authenticator:
    url: "{{ .Values.global.imageRegistry }}/tke-market/platform-authenticator:20_2607180954_stable_iaas_v4.0.3.0_0e570106_private"
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 1Gi
replicas: 1
