apiVersion: v1
kind: Service
metadata:
  labels:
    app: adp-crawler
  name: adp-crawler
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-7001-7001
      port: 7001
      protocol: TCP
      targetPort: 7001
  selector:
    app: adp-crawler
  type: ClusterIP
