images:
  adp-platform-metrology:
    url: "{{ .Values.global.imageRegistry }}/tke-market/platform-metrology:45_2607241748_stable_iaas_v4.0.3.0_70034e3f_private"
resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 2Gi
appName: adp-platform-metrology
replicas: 1
