images:
  adp-platform-metrology:
    url: "{{ .Values.global.imageRegistry }}/tke-market/platform-metrology:39_2606151838_stable_iaas_cos_355a47f4_private"
resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 2Gi
appName: adp-platform-metrology
replicas: 1
