images:
  adp-rag-exec:
    url: "{{ .Values.global.imageRegistry }}/tke-market/rag-exec:10_2607272306_stable_iaas_v4.0.3.0_14a8516a_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
