apiVersion: v1
kind: Service
metadata:
  labels:
    app: adp-agent-config
  name: adp-agent-config
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: adp-agent-config-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: adp-agent-config-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: adp-agent-config-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: adp-agent-config
  sessionAffinity: None
  type: ClusterIP