apiVersion: v1
kind: ServiceAccount
metadata:
  name: adp-plugin-pod-schedule
  namespace: {{ .Release.Namespace }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adp-plugin-pod-schedule
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale", "replicasets"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["endpoints", "pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adp-plugin-pod-schedule
subjects:
  - kind: ServiceAccount
    name: adp-plugin-pod-schedule
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: adp-plugin-pod-schedule
  apiGroup: rbac.authorization.k8s.io
