kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-plugin-pod-schedule
  namespace: {{ .Release.Namespace }}
data:
  error_en-US.json: |
    {
      "Pod配置不存在": "Pod configuration does not exist",
      "KubeConfig初始化失败": "Failed to initialize KubeConfig",
      "Pod资源加锁失败，请稍后重试": "Failed to lock Pod resource, please try again later",
      "Pod资源暂无可用，请稍后重试": "No available Pod resources, please try again later",
      "请求参数不合法": "Invalid request parameters",
      "没有已调度的Pod": "No scheduled Pods",
      "账号Pod达到上限": "Account Pod limit reached"
    }
  error_en.json: |
    {
      "Pod配置不存在": "Pod configuration does not exist",
      "KubeConfig初始化失败": "Failed to initialize KubeConfig",
      "Pod资源加锁失败，请稍后重试": "Failed to lock Pod resource, please try again later",
      "Pod资源暂无可用，请稍后重试": "No available Pod resources, please try again later",
      "请求参数不合法": "Invalid request parameters",
      "没有已调度的Pod": "No scheduled Pods",
      "账号Pod达到上限": "Account Pod limit reached"
    }

  error_zh-CN.json: |
    {
      "Pod配置不存在": "Pod配置不存在",
      "KubeConfig初始化失败": "KubeConfig初始化失败",
      "Pod资源加锁失败，请稍后重试": "Pod资源加锁失败，请稍后重试",
      "Pod资源暂无可用，请稍后重试": "Pod资源暂无可用，请稍后重试",
      "请求参数不合法": "请求参数不合法",
      "没有已调度的Pod": "没有已调度的Pod",
      "账号Pod达到上限": "账号Pod达到上限"
    }
  error_zh.json: |
    {
      "Pod配置不存在": "Pod配置不存在",
      "KubeConfig初始化失败": "KubeConfig初始化失败",
      "Pod资源加锁失败，请稍后重试": "Pod资源加锁失败，请稍后重试",
      "Pod资源暂无可用，请稍后重试": "Pod资源暂无可用，请稍后重试",
      "请求参数不合法": "请求参数不合法",
      "没有已调度的Pod": "没有已调度的Pod",
      "账号Pod达到上限": "账号Pod达到上限"
    }

  kube.yaml: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1EUXdNakEyTkRBMU5Wb1hEVE0xTURNek1UQTJOREExTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1Y0CkFFL2IyR2ZmcXNWTzRQait4aDJtRm82eXl0c0g3UU11ZUM0SjhTUUEyamdtWjZBUi9VOUdMZXhHVVhvUllBWHoKYXVFeXI1UzBTU2h5TG9UN0NTVG9SbUNndWZ5SEliRmx4akRjTXk1WUN2WURhVFN2MXNyZnc3Y0g0eHJMOTVsTQpjMHNMcWVGbW1HNkl2czgvemtUM05oQXo0eHlpaGhkc1VnT2hLcjhzVktBUmpGK3lYd1c1NVRPUFdNUkQ0cE84CjFaV1hsNlo2RnNCdFZVcG51cTBqdzE5VGp2b2lPc25HNXpqUm1CUVNLWmcyRUhwUW9pSmtkMm50S256eFY3d3UKbzZSdWRwa1RwWERIN1pUV0JzZitnTzNPdFpSUmg1QklVWE5Sa3NsblZ2d01tNzJsQWg5MDJWTWoySnMvR3VoegpsNE94WXNTVElDQzk0Qy9PN204Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0tVTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIajlxM3BKS01EelFEZ2ZsY3pUSlBmMURPbDAKNXdoQTBQOU5wWnZlZTFoTjNBVGwxQVFCVnNXYnBqQUlKL254MUlCMzIzcDdaRERLOTJqZ1l4QWRjL1pNR2hGOQpJWDVJbWdxSEpJd2o2WnIrdTdwcDZKU0t5WjlMUm1IMjFzQzF0RlpxcVJXQXFzM01veUxBbnhVYzZxMGhFSUtsCmNISyt3ckJtbHhUajQyUzFyUFZ6ckp1REdDeU1VRWJaZWx6R1RNakRRdVVwZkZHTzNLMjBuY21uWVdJQWd1eVAKUnk2aEpxenNMblVpbU40MWlyQmVYc2tNeXFYUXJEMC9LYytqbDk3TjlteDM2Q1g2bzU0THA4bzdkMWVJWHNWcwoyRG5FU2cxWDRPSFBZUFJHSkQ4L3J1KzN6R3dvVERlRkFrQVlmbVR2bHd1OHk3dFlHUzFqSTBTOVcxMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        server: https://9.139.235.44
      name: cls-pzlxvewk
    contexts:
    - context:
        cluster: cls-pzlxvewk
        user: "100030593772"
      name: cls-pzlxvewk-100030593772-context-default
    current-context: cls-pzlxvewk-100030593772-context-default
    kind: Config
    preferences: {}
    users:
    - name: "100030593772"
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lJU0lVTTJmRFBJSXd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1ESXdOalF6TXpkYUZ3MDBOVEEwTURJd05qUXpNemRhTURZeApFakFRQmdOVkJBb1RDWFJyWlRwMWMyVnljekVnTUI0R0ExVUVBeE1YTVRBd01ETXdOVGt6TnpjeUxURTNORE0xCk56WXlNVGN3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFJTWlBURWFhU0pWWVEKd0VLUW43dUZxMyt6ejNSN2VlN3B3Yjl6aUN5THdEOHU1K2J4Sjd3SEN5bzJob2NIOXJUUnJKSXpvbGFFZzBGbwpGRTloNFA4WDB5OTZzSVZYdWZwdzgrbEdEdmI5U1cvcWpDakdHSHRXVFI4eGN0NFFTUHhMVlhGWHVXNDVSVDFjCmFOeTJPaUhxRno4b1N1UzFaQWc2Mk94VVp0ZWJEeUtteHJFUWRrenVQeXh3N09uNC9UUG1nSVNBYTlxa2NDZlIKYTdUNHZmVytmQU9TeUIrd2Q2SGN1T214NU5ibG5CcFBvZjMraDNiWWpkYVVqVGlsM1BOVlhNUnlEbEpxdDltTwpwWk9sR0d6bVBIVlhlVGx1ZkFXcjF0YytVS1dQa1dudzl5bVJZWWNXaVl6aXhwTjN5dFpHcUlwUlhqOUhRSGFtCkRZc05UY2tkQWdNQkFBR2pQekE5TUE0R0ExVWREd0VCL3dRRUF3SUNoREFkQmdOVkhTVUVGakFVQmdnckJnRUYKQlFjREFnWUlLd1lCQlFVSEF3RXdEQVlEVlIwVEFRSC9CQUl3QURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpUQnVWblpnYWRVU2FlejBMd080bjg4UXVQUHZ2VEdFZDdxUFFxYVhWcjNvc21kMEl6b0ZMdDhKL2E5aCtQdlkxCnVqOTQyNFdqd2lpSm4xZTJxLzNZbUxwc0E4QXdTSUtQZXYyUjZ2VjljYTRVUUxZSFRaZlN1WkNFYkZackhiVkwKbVVya2tHR0Q3aWEzRDJhcTNEQXdDalVRa3kxc01RZit0ODdmVHFuejl2amhLUmVOV1RvMTdSa25xS3pRa1NvNgpoMWtzZFJMcndlUUd6T081eXRaSGhKWGw1bWx2R2tYYkJFeFI4N2hCbmw0QkNXRkk2bWQ0Ulhjd2lHUmpLQVVjCndFN1ozdlZ2Q1NhOWJQa3ExNXZreENEbGhpb0wrMVBFRU5JLzcreHlmQ2JTTHBKa2paL0N5SkZnNkJiRkcxVUEKUWlJaW40SFg4RmVkaWtEcWZhWGpwZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMFVtVDB4R21raVZXRU1CQ2tKKzdoYXQvczg5MGUzbnU2Y0cvYzRnc2k4QS9MdWZtCjhTZThCd3NxTm9hSEIvYTAwYXlTTTZKV2hJTkJhQlJQWWVEL0Y5TXZlckNGVjduNmNQUHBSZzcyL1VsdjZvd28KeGhoN1ZrMGZNWExlRUVqOFMxVnhWN2x1T1VVOVhHamN0am9oNmhjL0tFcmt0V1FJT3Rqc1ZHYlhtdzhpcHNheApFSFpNN2o4c2NPenArUDB6NW9DRWdHdmFwSEFuMFd1MCtMMzF2bndEa3NnZnNIZWgzTGpwc2VUVzVad2FUNkg5Ci9vZDIySTNXbEkwNHBkenpWVnpFY2c1U2FyZlpqcVdUcFJoczVqeDFWM2s1Ym53RnE5YlhQbENsajVGcDhQY3AKa1dHSEZvbU00c2FUZDhyV1JxaUtVVjQvUjBCMnBnMkxEVTNKSFFJREFRQUJBb0lCQVFDTGQyV3NIVElNYUJjUAplSitqTXQ3SzkvdFV2dVdYdHl6UDE0NFdsbU5oQ2M3UkdqYmE4NmlvWlBkUGVKeVpZUDBrVU1UbzVjQ1Q4OGZ0CmJNTnRyWHN3ekVueWo1bDhXWEljUFY1eGtsMWpjc0hDNG4zMWJMRWNWSzU1ekZ0UkxPSDc3Y2RuTnluTnZtZGkKb25xYWNPalN6NFVGKzhxbldpN2wwRkxFOS9lcjJ0ZkdEMTFEbExvay9ub1BzMmdTVzBKV1VReGVwelAySHBLTAozMEVzbDkvZTNZMWNXTlp4eXJiWkpLYnRNc29mTUlGRFJUMG1UREM3MkM5dktJR3lhY3hqTkd0ZzY4eHFBb29rClA5TFMyaFVlTTNSS2h4ZDVUSXNaazVNRi8zN3lkL2dUd2YycjBNVEhTbDgyR09TOUwyVVdCTnZVNFpEblNQZisKOWt5b0J1WTlBb0dCQVBvaW8wMzVuTWxOTW14a1l2UEpiQ1hLY01wMFR6ek94UVRnMGZ3VDlSOU5INUYwZVdteAoxZUxkM2d0b2FkZDduMS9IU3dmNU11dkphMHdWQzFsdEVNOEppdHhWZGtFa2xENG5OclhDc0s2d1Z4UFBhaUplCkNVWXp6RVVNVzhYdzJOTkFMbUZQV2I0MFZUNFFJZGNjS2tWczNlallJcmNDUlNsSWxZOVVsY2RMQW9HQkFOWXgKd3lja09lbUZBK3FOTEJOTzc4NWdtYjVPQUJQMWFaOG95dFpva1dnQ1VkRXR6SVJVaStiR0w4QjRIa0JWUFNRRgptS3l4YjFsSmJqSnBYNnRtRFpWZWhTSEtEY0gwTnpJMFhDSFY3UmVQT0VUZm5wUnFWb2J6QXNuOVg2YkJZMDJMCkgwZ1JqUnRMSlhJSUZaeEpzSUlZSktzRW5GMGR2TzU4d0VkSERPZzNBb0dCQU1weEdEdzJobGRCbkVxdm9JcHYKL1pCRVhLN3VIV2M0YmFvNkRwajJ5Zzl3U3RsZExCcUg3SFIxWG8xYkR6WnYvaGYxWXR0c0szTTdqQlNDZjdINwpuSHdEM0JmaEx4a2Y4cjZ1M0ErVko0dnFlajgxUWsvWVRhYzhxdGxEWEU5Q1V5bitLc3RrL2x2N1hQWWk5bEJ6Cm9oNllNcTJOcCtMMyttT2tOQzlScFBzckFvR0JBSWNRemd5cWpWSXhyR3lGSk52d0ZNdkFvbkljWVhRMGRxd0UKWHhPZzBNQVRabUJQVHYzTENvVTFSL3RJUTFzeDVPSUlIV1FZWnl5WVgwS3VxOE03RVNtMWRxSDk5WHJ1Y3JmWAp5SmtWZXZJMlA3YytnNUwzRXlUNXJES084WGdIem9TaFM5SjRMdENkTERtaDIyNjRFUE9ZSWRjdGl5UTBrbVNZCmllN29ZTDAxQW9HQVVNbkVXd3JIU2p4MHFkRERYYVpzRVZJNUQ4Rk9XOVpidm5aaWRpZGlWU3l4ckFJbCs3Q3oKd0tTOXE4VXdDV3hiWEVGc1JTWGEwT0pTSkwrSXF4WE1UMTVxTTV2Zkw1RUNVemhmZDRudEtoV1BscEVKbHQwUAprZVkzOGpWQjlrd1VjMmVtYXcvWjJsWGRwOGxjZTcwd0pCQWFkOU9Vblcxa2Q0dmFuaFgzeXNJPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  main.yaml: |
    redis_lock:
      wait_time: 60
      expire_time: 60
      lock_key: pod_lock_key
      lock_value: apply_pod

    pod_schedule:
      real_time: false
      max_try_count: 3
      try_wait_time: 5ms

      limit_uin_max_pod: true
      default_uin_max_pod: 20
      uin_limit_whitelist:
        "700000576145": 8 # 测试

    pod_info:
      type: lb
      namespace: {{ .Release.Namespace }}
      service_name: mcp-sandbox

      max_pods: 20      # 最大数量
      min_pods: 10       # 最小数量
      upper_thr: 0.8    # 扩容阈值
      lower_thr: 0.3    # 缩容阈值

      expired_time: 600 # 过期时间（单位：s）

      server_config:
        1: # 沙箱MCP
          port: 8000
          url_format: "http://%s:%d/runtime_mcp/sse"
        2: # 沙箱VNC
          port: 8080
          url_format: "http://%s:%d/vnc_lite.html"
        3: # 沙箱CODE
          port: 9000
          url_format: "http://%s:%d/execute"

  placeholder.yaml: |
    REDIS_TARGET: 

    # main.yaml

    # pod??????
    POD_SCHEDULE:
      real_time: false
      max_try_count: 3
      try_wait_time: 5ms

      limit_uin_max_pod: true
      default_uin_max_pod: 4
      uin_limit_whitelist:
        100024239198: 5 # halelv
        100034812856: 20 # hank
        100034812935: 20 # hank

    # pod????
    POD_INFO:
      type: lb
      namespace: mcp-sandbox
      service_name: bot-mcp-sandbox
      max_pods: 100
      min_pods: 50
      upper_thr: 0.8
      lower_thr: 0.3
      expired_time: 600
      server_config:
        1:
          port: 8000
          url_format: "http://%s:%d/runtime_mcp/sse"
        2:
          port: 8080
          url_format: "http://%s:%d/vnc_lite.html"
        3:
          port: 9000
          url_format: "http://%s:%d/execute"

    # client.yaml

  trpc_go.yaml: |
    global:                                   #全局配置
      namespace: Development                  #环境类型，分正式production和非正式development两种类型
      env_name: dev                           #环境名称，非正式环境下多环境的名称
      enable_set: false               #是否启用set
      full_set_name: adp         #set名
      local_ip: ${POD_IP}
      container_name: ${POD_NAME}
    server:                                   #服务端配置
      app: adp                                #业务的应用名
      server: plugin-pod-schedule             #进程服务名
      bin_path: /app/bin/                     #二进制可执行文件和框架配置文件所在路径
      conf_path: /app/conf/                   #业务配置文件所在路径
      data_path: /app/data/                   #业务数据文件所在路径
      filter:                                 #针对所有service处理函数前后的拦截器列表
        - recovery                            #拦截框架创建的业务处理协程panic
      admin:
        ip: ${POD_IP}                         # admin 的 ip，配置网卡 nic 也可以
        port: 8081                            # admin 的 port，必须同时配置这里的 ip port 才会启动 admin
      service:                                #业务服务提供的service，可以有多个
        - name: trpc.KEP.resource-schedule-server.ScheduleServer  #service的路由名称
          ip: ${POD_IP}                       #服务监听ip地址 可使用占位符 ${ip},ip和nic二选一，优先ip
          port: 8000                          #服务监听端口 可使用占位符 ${port}
          network: tcp                        #网络监听类型  tcp udp
          protocol: trpc                      #应用层协议 trpc http
          timeout: 0                          #请求最长处理时间 单位 毫秒
          server_async: true                  #开启异步处理
          idletime: 600000                    # idletime，设置tcp空闲等待时间，避免耗时过长的操作导致trpc-go将tcp关闭
        - name: trpc.KEP.resource-schedule-server.syncNodes  # service 的路由名称
          ip: ${POD_IP}
          port: 9090                          # 服务监听端口 可使用占位符 ${port}
          network: "* 0/1 * * * ?startAtOnce=1&scheduler=syncNodes"  # 任务调度策略
          protocol: timer                     # 设置服务类型为定时器服务
          timeout: 10000
    plugins:                                  #插件配置
      log:                                    #日志配置
        default:                              #默认日志的配置，可支持多输出
          - writer: console                   #控制台标准输出 默认
            level: debug                      #标准输出日志的级别
          - writer: file                      # 本地文件日志
            level: debug                      # 标准输出日志的级别，开发提测环境可以用debug，线上建议用info
            writer_config:                    # 本地文件输出具体配置
              filename: /app/logs/trpc.log    # 本地文件滚动日志存放的路径
              max_size: 200                   # 本地文件滚动日志大小，单位 MB
              max_backups: 10                 # 最大日志文件数
              max_age: 7                      # 最大日志保留天数
              compress: false                 # 日志文件是否压缩
      config:
        file:
          providers:
            - name: rainbow
              path: /app/conf/
            - name: global
              appid: ${RAINBOW_APP_ID}        # appid
              group: global                   # 配置所属组
              type: kv                        # 七彩石数据格式, kv(默认), table
              env_name: ${RAINBOW_ENV_NAME}
              timeout: 2000
              enable_client_provider: true
      registry:                               #服务注册配置
        polaris:                              #北极星名字注册服务的配置
      i18n:
        i18n:
          default_lang: zh
          data_provider:
            type: rainbow
            prefix: resource-schedule
            error_prefix: error
      selector:                               #针对用户自定义的selector的配置
        polaris:                              #针对polaris整体api的内部配置
          protocol: grpc                      #名字服务远程交互协议类型
    client:                                   #客户端调用的后端配置
      namespace: Production                  #针对所有后端的环境
      stream_filter:
      service:
        - name: redis.resource-schedule-server
          network: tcp
          target: ip://${INFRA_MIDDLEWARES_REDIS_0_HOSTS}:6379/2
          password: ${INFRA_MIDDLEWARES_REDIS_0_PASSWORD}
          timeout: 800
