{
 "title": "HDFS JournalNode",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "journalnode",
    "label": "JournalNode",
    "query": "label_values(Hadoop_JournalNode_ClassLoading_Verbose,pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Batches Written",
   "type": "singlestat",
   "description": "Total number of batches written since startup",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_JournalNode_BatchesWritten{pod=~\"$journalnode\"}"
    }
   ]
  },
  {
   "title": "Txns Written",
   "type": "singlestat",
   "description": "Total number of transactions written since startup",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_JournalNode_TxnsWritten{pod=~\"$journalnode\"}"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "singlestat",
   "description": "Total number of bytes written since startup",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_JournalNode_BytesWritten{pod=~\"$journalnode\"}"
    }
   ]
  },
  {
   "title": "Batches Written While Lagging",
   "type": "singlestat",
   "description": "Total number of batches written where this node was lagging",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_JournalNode_BatchesWrittenWhileLagging{pod=~\"$journalnode\"}"
    }
   ]
  },
  {
   "title": "Last Writer Epoch",
   "type": "singlestat",
   "description": "Current writer’s epoch number",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_JournalNode_LastWriterEpoch{pod=~\"$journalnode\"}"
    }
   ]
  },
  {
   "title": "Current Lag Txns",
   "type": "singlestat",
   "description": "The number of transactions that this JournalNode is lagging",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_JournalNode_CurrentLagTxns{pod=~\"$journalnode\"}"
    }
   ]
  },
  {
   "title": "Last Promised Epoch",
   "type": "singlestat",
   "description": "The last epoch number which this node has promised not to accept any lower epoch, or 0 if no promises have been made",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_JournalNode_LastPromisedEpoch{pod=~\"$journalnode\"}"
    }
   ]
  },
  {
   "title": "Last Written TxId",
   "type": "singlestat",
   "description": "The highest transaction id stored on this JournalNode",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_JournalNode_LastWrittenTxId{pod=~\"$journalnode\"}"
    }
   ]
  },
  {
   "title": "Last Journal Time",
   "type": "singlestat",
   "description": "The timestamp of last successfully written transaction",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "Hadoop_JournalNode_LastJournalTimestamp{pod=~\"$journalnode\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{pod_name=~\"kdl-hadoop-hdfs-jn-(\\\\d+)\"}[5m])*100) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"kdl-hadoop-hdfs-jn-(\\\\d+)\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Syncs 60s Num Ops",
   "type": "graph",
   "description": "Number of sync operations (1 minute granularity)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "Hadoop_JournalNode_Syncs60sNumOps{}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}