apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ti.cloud.tencent.com/resource-quota: unlimited
    configmap.reloader.stakater.com/reload: {{ .Release.Name }}-chat-manage
    {{- if .Values.global.customAnnotations }}
    {{- range $key, $value := .Values.global.customAnnotations }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
  labels:
    app: adp-chat-manage
    {{- if .Values.global.customLabels }}
    {{- range $key, $value := .Values.global.customLabels }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
  name: adp-chat-manage
  namespace: {{ .Release.Namespace }}
spec:
  {{- if eq .Values.global.clusterSize "minimal" }}
  replicas: 1
  {{- else if eq .Values.global.clusterSize "standard" }}
  replicas: 2
  {{- else }}
  replicas: 3
  {{- end }}
  selector:
    matchLabels:
      app: adp-chat-manage
  template:
    metadata:
      labels:
        app: adp-chat-manage
        {{- if .Values.global.customLabels }}
        {{- range $key, $value := .Values.global.customLabels }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
        {{- end }}
      {{- if .Values.global.customAnnotations }}
      annotations:
        {{- range $key, $value := .Values.global.customAnnotations }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
      {{- end }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - adp-chat-manage
              topologyKey: kubernetes.io/hostname
            weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: GPUName
                    operator: DoesNotExist
            - weight: 50
              preference:
                matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - lke
      {{- if eq (include "needInitContainer" .) "true" }}
      serviceAccountName: adp-reader
      {{- end }}
      initContainers:
        {{- include "dependencyChecker.initContainer" . | nindent 8 }}
      containers:
        - env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: version
              value: "20230925"
            - name: DEPLOYMENT_ENVIRONMENT
              value: "TKE"
            - name: ADP_HOST
              value: "{{ .Values.global.scheme }}://{{ .Values.global.clb }}"
            {{- if .Values.global.components.s3.cos.stsKey }}
            - name: ADP_ASSUME_ROLE_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.components.s3.cos.stsKey }}
                  key: ADP_ASSUME_ROLE_SECRET_ID
                  optional: true
            - name: ADP_ASSUME_ROLE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.components.s3.cos.stsKey }}
                  key: ADP_ASSUME_ROLE_SECRET_KEY
                  optional: true
            {{- end }}
          image: {{ include "resolveImageUrl" (dict "url" (index .Values.images "adp-chat-manage").url "context" .) }}
          imagePullPolicy: Always
          # command: ["sh","-c", "crond start; touch /var/log/log.txt && tail -f /var/log/log.txt"]
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 20
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 9090
            timeoutSeconds: 2
          name: adp-chat-manage
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 20
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 9090
            timeoutSeconds: 2
          {{- if eq .Values.global.clusterSize "minimal" }}
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "125m"
              memory: "512Mi"
          {{- else if eq .Values.global.clusterSize "standard" }}
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          {{- else }}
          resources:
            limits:
              cpu: "1"
              memory: "4Gi"
            requests:
              cpu: "500m"
              memory: "2Gi"
          {{- end }}
          securityContext:
            capabilities:
              add:
                - SYS_RESOURCE
                - NET_ADMIN
                - SYS_ADMIN
                - IPC_LOCK
                - SYS_PTRACE
            privileged: false
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /app/logs
              name: logdata
              subPathExpr: $(POD_NAME)
            - mountPath: /app/conf/trpc_go.yaml
              name: config
              subPath: trpc_go.yaml
            - mountPath: /app/conf/application.yaml
              name: config
              subPath: application.yaml
            - mountPath: /app/conf/placeholder.yaml
              name: config
              subPath: placeholder.yaml
            - mountPath: /app/conf/adp.yaml
              name: config
              subPath: adp.yaml
            - mountPath: /app/conf/agent.yaml
              name: config
              subPath: agent.yaml
            - mountPath: /app/conf/chat_en-US.json
              name: config
              subPath: chat_en-US.json
            - mountPath: /app/conf/chat_zh-CN.json
              name: config
              subPath: chat_zh-CN.json
            - mountPath: /app/conf/chat_zh.json
              name: config
              subPath: chat_zh.json
            - mountPath: /app/conf/error_en-US.json
              name: config
              subPath: error_en-US.json
            - mountPath: /app/conf/error_zh-CN.json
              name: config
              subPath: error_zh-CN.json
            - mountPath: /app/scurl.yaml
              name: rainbow-comm
              subPath: scurl.yaml
            - mountPath: /app/conf/infrastructure.yaml
              name: infrastructure
              subPath: infrastructure.yaml
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        {{- include "dependencyChecker.volumes" . | nindent 8 }}
        - hostPath:
            path: /data/ti-platform/log/chat
            type: DirectoryOrCreate
          name: logdata
        - configMap:
            name: chat-application
          name: config-application
        - configMap:
            defaultMode: 420
            name:  {{ .Release.Name }}-chat-manage
          name: config
        - configMap:
            name: rainbow-comm
          name: rainbow-comm

        - configMap:
            defaultMode: 420
            name: infrastructure
          name: infrastructure
