apiVersion: v1
kind: Service
metadata:
  labels:
    app: adp-kb-file-manager
  name: adp-kb-file-manager
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: tcp-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: tcp-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: tcp-9091
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    app: adp-kb-file-manager
  sessionAffinity: None
  type: ClusterIP
