tad:
  type: helm
  namespace: ti-base
  global:
    productType: lke
images:
  ti-auth-web:
    url: "{{ .Values.global.imageRegistry }}/tke-market/ti-tiauth-prod-production:14_release_stable-v4.0.0.0_2607202230-19cd916"
env: TEST
namespace: ti-base
imagePullSecretName: qcloudregistrykey
SSOLoginPage: false
ssoLogoutUrl: ''
ssoTokenKey: ''
replicas: 1
