images:
  entity-extractor-server-sand-box:
    url: "{{ .Values.global.imageRegistry }}/tke-market/smartassistant.entityextractorserversandbox:default-b-13-f_2.0.0.32_20260503183022_Tag_EntityExtractorServer_20250708_01_iaas"
replicas: 1
