images:
  entity-extractor-server-sand-box:
    url: "{{ .Values.global.imageRegistry }}/tke-market/smartassistant.entityextractorserversandbox:default-b-14-f_2.0.0.35_20260723112946_Tag_EntityExtractorServer_20250708_01_iaas"
replicas: 1
