kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-app-channel-msg
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |
    sync_time_out: 1800
    sync_stream_time_out: 5
    msg_menu_text_limit: 45
    msg_menu_item_num_limit: 10
    create_session_words:
      "新建对话": true
      "/new": true
      "/NEW": true
    reset_session_words:
      "清除上下文关联": true
      "/clear": true
      "/CLEAR": true
    session_secret_id: ${INFRA_MIDDLEWARES_S3_COS_SECRETID}
    session_secret_key: ${INFRA_MIDDLEWARES_S3_COS_SECRETKEY}
    session_end_point: ${SESSIONS_END_POINT}
    session_region: "${INFRA_MIDDLEWARES_S3_COS_REGION}"
    system_msg_err: "[System] Internal service error. Please try again later."
    system_msg_creation_session_success: "[System] New conversation started."
    system_msg_creation_session_failed: "[System] Failed to create new conversation. Please try again later."
    system_msg_reset_session_success: "[System] Context cleared."
    system_msg_reset_session_failed: "[System] Failed to clear context. Please try again later."
    channel_type_map:
      wechat: 10000
      wecom: 10002
      wxkf: 10004
      wecomrobot: 10009
      line: 10011
      telegram: 10012
    component_app_id: ${COMPONENT_APP_ID}
    wx_authorize_callback_host: {{ .Values.global.scheme }}://{{ .Values.global.clb }}  #需要填写用户自己申请的域名  需要能反代回到msg服务
    wx_authorize_callback: "/online/channel/callback/wx/authorize"
    sse_chat_path: /v1/qbot/chat/sse
    redirect_url: {{ .Values.global.scheme }}://{{ .Values.global.clb }}/adp/#/app/knowledge/release/channel?appid=%d&appType=knowledge_qa&spaceId=default_space
    redirect_url_with_space_id: {{ .Values.global.scheme }}://{{ .Values.global.clb }}/adp/#/app/knowledge/release/channel?appid=%d&appType=knowledge_qa&spaceId=%s
    get_wx_auth_code_max_limit : 3
    streaming_throttle: 250
    not_support_msg: Unsupported message type
    env: lke
    yuanqi_api_key: xxxx
    publish_yuanqi_url: /admin_api/v2/agent/publish/yuanqi
    publish_yingyongbao_url: /admin_api/v2/agent/publish/yinyongbao
    wx_nginx_l5: lke_https_forward_proxy
    wx_nginx_namespace: Test
    cos_secret_id: ${INFRA_MIDDLEWARES_S3_COS_SECRETID}
    cos_secret_key: ${INFRA_MIDDLEWARES_S3_COS_SECRETKEY}
    cos_bucket: ${INFRA_MIDDLEWARES_S3_COS_BUCKET}
    cos_region: "${INFRA_MIDDLEWARES_S3_COS_REGION}"
    get_ip_max_limit : 2000
    is_open_ip_max_limit_switch : false
    message_interval_time: 800ms
    wechat_msg_time_out: 20m
    deployment_mode:
      mode: "adp"
    default_greeting_content: "You can ask me:"
    uncertified_wx_reply_config:
      uncertified_reply_in_5s_wx_app_ids:
      continue_keywords:
        - "继续"
        - "继续。"
        - "【继续】"
        - "请继续"
        - "继续发"
      no_reply_notice: "正在思考中……可回复【继续】获取回答内容" # 5s 或 15s未回复提示
      reply_not_complete_notice: "回答未完成，可回复【继续】获取更多回答内容" # 回答未完成提示
      discard_continue_notice: "模型正在思考中，请稍后回复【继续】获取更多回答内容" # 忽略继续关键词通知
    storage:
      type: cos
      subPath: {{ .Values.global.components.s3.cos.subPath | quote }}
      cos_map:
        realtime:
          secret_id: {{ .Values.global.components.s3.cos.secretId }}
          secret_key: {{ .Values.global.components.s3.cos.secretKey }}
          app_id: {{ .Values.global.components.s3.cos.appId | quote }}
          region: {{ .Values.global.components.s3.cos.region }}
          bucket: {{ .Values.global.components.s3.cos.bucket }}
          domain: {{ .Values.global.components.s3.cos.domain }}
          expire_time: {{ .Values.global.components.s3.cos.expireTime | default "30m" }}
          credential_time: 10m

    # line 相关配置
    line_config:
      max_msg_per_push: 5
      text_buffer_max_rune: 1000
      loading_seconds: 60

    # telegram 相关配置
    telegram_config:
      text_buffer_max_rune: 1000

    # 构建菜单描述文本
    menu_select_text: "Please select an option:"


  channel-msg_en-US.json: |
    {}
  channel-msg_zh-CN.json: |
    {}
  env.yaml: |
    version: 2.0.0 # 固定值，不需要修改
    kind: env # 固定值，不需要修改
    metadata:
        name: formal # 环境名称 [选填]

  error_en-US.json: |
    {
      "参数错误": "Invalid Parameter",
      "get请求签名校验错误": "Get Request Signature Verification Error",
      "GetAgentInfo fail": "Get Agent Info Fail",
      "请求签名校验错误": "Request Signature Verification Error",
      "解密后参数解析错误": "Decrypted Parameter Parsing Error",
      "get msg_provider failed, need register plugins": "Failed to get msg_provider, need to register plugins",
      "unknown http method": "Unknown Http Method",
      "no data available": "No Data Available",
      "wxPub c2b msg type not support": "Wx Pub C2B Msg Type Not Support",
      "公众号已被当前应用绑定，请先解绑后再操作": "Public Account Already Bound Please Unbind First",
      "wx pub request url parse error": "Wechat Pub request URL parse error",
      "wx pub request url not include appid": "Wx Pub Request Url Not Include Appid",
      "wxPub b2c call wx failed": "Wechat Pub B2C Call Wechat Failed",
      "wxPub c2b xml parse error": "Wx Pub C2B Xml Parse Error",
      "wx auth code is empty": "Wechat auth code is empty",
      "appBiz id is empty": "App Biz Id Is Empty",
      "call wx get pre auth code failed": "Call Wx Get Pre Auth Code Failed",
      "达到每分钟最大授权次数，请稍后再试": "Reached Max Auth Limit Per Minute, Please Try Later",
      "call wecom send msg failed": "Call Wecom Send Msg Failed",
      "ai response body is empty": "AI Response body is empty",
      "msg id duplication has been intercepted": "Msg Id Duplication Has Been Intercepted",
      "input cos uuid is intercepted": "Input Cos Uuid Is Intercepted",
      "down data format error": "Down Data Format Error",
      "env环境未注册": "Env Environment Not Registered",
      "syncType传参错误": "Sync Type Parameter Error",
      "修改渠道状态处理失败": "Failed to process channel status modification",
      "获取公众号关联的应用信息失败": "Failed to get associated info for official account",
      "获取公众号渠道信息失败": "Get Public Account Channel Info Failed",
      "获取渠道信息失败": "Get Channel Info Failed",
      "检查渠道发布状态失败": "Failed to check channel release status",
      "获取元器配置失败": "Get Yuan Config Failed",
      "c2b pull wxkf msg failed": "C2B Pull Wxkf Msg Failed",
      "c2b wxkf msg event not support": "C2B Wxkf Msg Event Not Support",
      "消息发送失败，系统错误": "Message sending failed, system error",
      "wxkf set next cursor failed": "Wxkf Set Next Cursor Failed",
      "wxkf get cursor failed": "Wxkf Get Cursor Failed",
      "wxkf send msg finish": "Failed to send message to Wechat Customer Service",
      "wxkf info no data available": "No Wechat Customer Service data available",
      "拉取微信客服形象失败，确认已经开通微信客服": "Failed to call Wechat Customer Service, Please confirm it's enabled",
      "无效的企业ID或Secret，请确认填写是否正确": "Invalid Corp Id Or Secret, Please Confirm if Correct",
      "get wxkf id info failed": "Failed to get Wechat Customer Service Info",
      "get corp id from ctx failed": "Get Corp Id From Ctx Failed",
      "没有可操作的渠道": "No Operable Channel Available",
      "发送失败:微信暂不支持该文件类型": "Sending failed: WeChat currently does not support this file type",
      "发送失败:素材超过微信最大10MB限制": "Sending failed: Material exceeds the max 10MB limit for wechat",
      "不合法的媒体文件id": "Invalid Media File Id"
    }
  error_zh-CN.json: |
    {
      "参数错误": "参数错误",
      "get请求签名校验错误": "get请求签名校验错误",
      "GetAgentInfo fail": "GetAgentInfo fail",
      "请求签名校验错误": "请求签名校验错误",
      "解密后参数解析错误": "解密后参数解析错误",
      "get msg_provider failed, need register plugins": "get msg_provider failed, need register plugins",
      "unknown http method": "unknown http method",
      "no data available": "no data available",
      "wxPub c2b msg type not support": "wxPub c2b msg type not support",
      "公众号已被当前应用绑定，请先解绑后再操作": "公众号已被当前应用绑定，请先解绑后再操作",
      "wx pub request url parse error": "wx pub request url parse error",
      "wx pub request url not include appid": "wx pub request url not include appid",
      "wxPub b2c call wx failed": "wxPub b2c call wx failed",
      "wxPub c2b xml parse error": "wxPub c2b xml parse error",
      "wx auth code is empty": "wx auth code is empty",
      "appBiz id is empty": "appBiz id is empty",
      "call wx get pre auth code failed": "call wx get pre auth code failed",
      "达到每分钟最大授权次数，请稍后再试": "达到每分钟最大授权次数，请稍后再试",
      "call wecom send msg failed": "call wecom send msg failed",
      "ai response body is empty": "ai response body is empty",
      "msg id duplication has been intercepted": "msg id duplication has been intercepted",
      "input cos uuid is intercepted": "input cos uuid is intercepted",
      "down data format error": "down data format error",
      "env环境未注册": "env环境未注册",
      "syncType传参错误": "syncType传参错误",
      "修改渠道状态处理失败": "修改渠道状态处理失败",
      "获取公众号关联的应用信息失败": "获取公众号关联的应用信息失败",
      "获取公众号渠道信息失败": "获取公众号渠道信息失败",
      "获取渠道信息失败": "获取渠道信息失败",
      "检查渠道发布状态失败": "检查渠道发布状态失败",
      "获取元器配置失败": "获取元器配置失败",
      "c2b pull wxkf msg failed": "c2b pull wxkf msg failed",
      "c2b wxkf msg event not support": "c2b wxkf msg event not support",
      "消息发送失败，系统错误": "消息发送失败，系统错误",
      "wxkf set next cursor failed": "wxkf set next cursor failed",
      "wxkf get cursor failed": "wxkf get cursor failed",
      "wxkf send msg finish": "wxkf send msg finish",
      "wxkf info no data available": "wxkf info no data available",
      "拉取微信客服形象失败，确认已经开通微信客服": "拉取微信客服形象失败，确认已经开通微信客服",
      "无效的企业ID或Secret，请确认填写是否正确": "无效的企业ID或Secret，请确认填写是否正确",
      "get wxkf id info failed": "get wxkf id info failed",
      "get corp id from ctx failed": "get corp id from ctx failed",
      "没有可操作的渠道": "没有可操作的渠道",
      "发送失败:微信暂不支持该文件类型": "发送失败:微信暂不支持该文件类型",
      "发送失败:素材超过微信最大10MB限制": "发送失败:素材超过微信最大10MB限制",
      "不合法的媒体文件id": "不合法的媒体文件id"
    }
  placeholder.yaml: |
    NAMESPACE: Production
    ENV_NAME: formal
    RAINBOW_ENV_NAME: formal
    RAINBOW_GROUP: channel-msg-svr
    #没有引用，清理
    TRPC_KEP_CHANNEL_MSG_SVR_HTTP_TOKEN: 
    #没有引用，清理
    TRPC_KEP_CHANNEL_MSG_SVR_TRPC_TOKEN: 
    #没有引用，清理
    TRPC_KEP_TRPC_KEP_CHANNEL_MSG_SVR_API_TOKEN: 
    TRPC_AI_CLIENT_TARGET: dns://testwss.testsite.woa.com:443
    SESSIONS_END_POINT: lke.pre.tencentcloudapi.woa.com
    COMPONENT_APP_ID: {{ dig "wechat" "componentAppId" "" .Values.global }}
    WX_AUTHORIZE_CALLBACK_HOST: https://tde.xiaowei.cloud.tencent.com
    WX_AUTHORIZE_CALLBACK: /channel/callback/wx/test/authorize
    IS_PRIVATE: true
  trpc_go.yaml: |
    global:
      namespace: ${POD_NAMESPACE}
      env_name: dev
      enable_set: false
      full_set_name: adp
      local_ip: ${POD_IP}
      container_name: ${POD_NAME}
    server:
      app: adp
      server: app-channel
      bin_path: /usr/local/trpc/bin/
      conf_path: /usr/local/trpc/conf/
      data_path: /usr/local/trpc/data/
      filter:
        - recovery
        - i18n-adp
        - debuglog
        - cle-route-propagator
        - opentelemetry
      admin:
        ip: ${POD_IP}
        port: 8081
      service:
        - name: trpc.KEP.channel-msg-svr.HTTP
          ip: ${POD_IP}
          port: 8000
          network: tcp
          protocol: http_no_protocol
          timeout: 50000
          server_async: true
          idletime: 600000
        - name: trpc.KEP.channel-msg-svr.trpc
          ip: ${POD_IP}
          port: 8001
          network: tcp
          protocol: trpc
          timeout: 50000
          server_async: true
          idletime: 600000
          filter:
            - session
            - permission
        - name: trpc.KEP.trpc.KEP.channel-msg-svr.Api
          ip: ${POD_IP}
          port: 8002
          network: tcp
          protocol: trpc
          timeout: 50000
          server_async: true
          idletime: 600000
    plugins:
      config:
        file:
          providers:
            - name: rainbow
              path: /app/conf/
            - name: rainbow-comm
              path: /app/conf/
            - name: global
              appid: ${RAINBOW_APP_ID}
              group: global
              type: kv
              env_name: ${RAINBOW_ENV_NAME}
              timeout: 2000
              enable_client_provider: true
      telemetry:
        opentelemetry:
          addr: {{ ((.Values.global.observability).apm).otlp | default "" }}
          tenant_id: adp
          sampler:
            fraction: 1
          traces:
            disable_trace_body: false
          metrics:
            {{- if ((.Values.global.observability).apm).registry }}
            registry_endpoints: ["{{ .Values.global.observability.apm.registry}}"]
            {{- end }}
          logs:
            enabled: true
            level: "debug"
            trace_log_mode: "disable"
          {{- if ((.Values.global.observability).apm).attributes }}
          attributes:
            {{- range $key, $value := .Values.global.observability.apm.attributes }}
          - key: {{ $key }}
            value: {{ $value }}
            {{- end }}
          {{- end }}
      log:
        default:
          - writer: console
            level: debug
          - writer: file
            level: info
            writer_config:
              filename: /app/log/trpc.log
              max_size: 10
              max_backups: 10
              max_age: 7
              compress: false
      registry:
        polaris:
          register_self: false
          heartbeat_interval: 3000
          heartbeat_timeout: 1000
          service:
            - name: trpc.KEP.channel-msg-svr.HTTP
              namespace: ${POD_NAMESPACE}
              token: xxxxxxxxxxxx  #safe
            - name: trpc.KEP.channel-msg-svr.trpc
              namespace: ${POD_NAMESPACE}
              token: xxxxxxxxxxxx #safe
            - name: trpc.KEP.trpc.KEP.channel-msg-svr.Api
              namespace: ${POD_NAMESPACE}
              token: xxxxxxxxxxxx #safe
      selector:
        polaris:
          protocol: grpc
          enable_servicerouter: true
          enable_trans_meta: true
      i18n:
        i18n-adp:
          default_lang: zh-CN
          supported_languages:
            - zh-CN
            - en-US
          data_provider:
            type: rainbow
            prefix: channel-msg
            error_prefix: error
            char_scaling_factor:
              zh-CN: 1
              en-US: 3
    client:
      filter:
        - cle-route-propagator
        - opentelemetry
      service:
        - name: mysql.qbot.admin
          target: "dsn://${INFRA_MIDDLEWARES_DB_0_USER}:${INFRA_MIDDLEWARES_DB_0_PASSWORD}@tcp(${INFRA_MIDDLEWARES_DB_0_HOST}:${INFRA_MIDDLEWARES_DB_0_PORT})/db_llm_robot?charset=utf8mb4&timeout=1s&parseTime=true&interpolateParams=true&loc=Local"
        - name: tdsql.tcadp.channel
          target: "dsn://${INFRA_MIDDLEWARES_DB_0_USER}:${INFRA_MIDDLEWARES_DB_0_PASSWORD}@tcp(${INFRA_MIDDLEWARES_DB_0_HOST}:${INFRA_MIDDLEWARES_DB_0_PORT})/db_llm_robot?charset=utf8mb4&timeout=1s&parseTime=true&interpolateParams=true&loc=Local"
        - name: redis.qbot.admin
          network: tcp
          target: "ip://${INFRA_MIDDLEWARES_REDIS_0_HOSTS}:6379/2"
          password: ${INFRA_MIDDLEWARES_REDIS_0_PASSWORD}
          timeout: 800
        - name: wx.nginx
          target: ip://adp-app-channel-proxy.{{ .Release.Namespace }}.svc.cluster.local:8000
          network: tcp
          protocol: http
          timeout: 20000
        - name: wx.resource.nginx
          target: ip://adp-app-channel-proxy.{{ .Release.Namespace }}.svc.cluster.local:8001
          network: tcp
          protocol: http
          timeout: 20000
        - name: trpc.KEP.channel_token_svr.ChannelTokenService
          network: tcp
          protocol: trpc
          target: ip://adp-app-channel-token.{{ .Release.Namespace }}.svc.cluster.local:8000
          timeout: 2000
        - name: trpc.KEP.bot_admin_config_server.Admin
          network: tcp
          protocol: trpc
          target: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9090
          timeout: 5000
        - callee: trpc.ai.client
          name: trpc.ai.client
          network: tcp
          protocol: http
          target: dns://{{ .Values.global.clb }}:{{ ternary 443 80 (eq .Values.global.scheme "https") }}
          timeout: 600000
        - callee: trpc.KEP.bot_admin_config_server.Login
          target: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9091
          protocol: trpc
          timeout: 20000
        - name: trpc.KEP.bot_task_config_server.TaskConfig
          target: ip://adp-workflow-config.{{ .Release.Namespace }}.svc.cluster.local:8000
          timeout: 5000
        - callee: trpc.KEP.bot_knowledge_config_server.Api
          name: trpc.KEP.bot-knowledge-config-server.Api
          target: ip://adp-kb-config.{{ .Release.Namespace }}.svc.cluster.local:9092
          protocol: trpc
          timeout: 5000
        # admin Login
        - callee: trpc.KEP.bot_admin_config_server.Api
          target: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9092
          protocol: trpc
          timeout: 20000
        # 知识库-内部接口
        - callee: trpc.adp.kb_config.Api
          name: trpc.KEP.bot-knowledge-config-server.Api
          target: ip://adp-kb-config.{{ .Release.Namespace }}.svc.cluster.local:9092
          protocol: trpc
          timeout: 5000
        # 工作流配置端-内部接口
        - callee: trpc.adp.workflow_config.WorkflowConfig
          target: ip://adp-workflow-config.{{ .Release.Namespace }}.svc.cluster.local:8000
          timeout: 5000
        # admin API
        - callee: trpc.adp.app_admin_proxy.Api
          target: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9092
          protocol: trpc
          timeout: 20000
        # admin Login
        - callee: trpc.adp.app_admin_proxy.Login
          target: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9091
          protocol: trpc
          timeout: 20000
        - callee: trpc.adp.chat_manage.Chat
          name: trpc.adp.chat_manage.Chat
          target: ip://adp-chat-manage.{{ .Release.Namespace }}.svc.cluster.local:9091
          protocol: trpc
          timeout: 20000
        - callee: trpc.adp.platform_manager.Login
          target: ip://adp-platform-manager.{{ .Release.Namespace }}.svc.cluster.local:9091
          protocol: trpc
          timeout: 20000
        - name: trpc.http.cos.Access
          network: tcp
          protocol: http
          target: dns://cos-internal.${INFRA_MIDDLEWARES_S3_COS_REGION}.tencentcos.cn
          timeout: 5000
