apiVersion: apps/v1
kind: Deployment
metadata:
  name: adp-plugin-code-interpret
  namespace: {{ .Release.Namespace }}
  annotations:
    ti.cloud.tencent.com/resource-quota: unlimited
    configmap.reloader.stakater.com/reload: {{ .Release.Name }}-plugin-code-interpret
    {{- if .Values.global.customAnnotations }}
    {{- range $key, $value := .Values.global.customAnnotations }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
  labels:
    app: adp-plugin-code-interpret
    app.kubernetes.io/name: adp-plugin-code-interpret
    {{- if .Values.global.customLabels }}
    {{- range $key, $value := .Values.global.customLabels }}
    {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
    {{- end }}
spec:
  {{- if eq .Values.global.clusterSize "minimal" }}
  replicas: 1
  {{- else if eq .Values.global.clusterSize "standard" }}
  replicas: 2
  {{- else }}
  replicas: 3
  {{- end }}
  selector:
    matchLabels:
      app: adp-plugin-code-interpret
  template:
    metadata:
      labels:
        app: adp-plugin-code-interpret
        {{- if .Values.global.customLabels }}
        {{- range $key, $value := .Values.global.customLabels }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
        {{- end }}
      {{- if .Values.global.customAnnotations }}
      annotations:
        {{- range $key, $value := .Values.global.customAnnotations }}
        {{ $key }}: {{ $value | toString | quote }}
        {{- end }}
      {{- end }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - adp-plugin-code-interpret
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: GPUName
                    operator: DoesNotExist
            - weight: 50
              preference:
                matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - lke
      serviceAccountName: adp-plugin-code-interpret-controllers
      terminationGracePeriodSeconds: 90
      {{- if eq (include "needInitContainer" .) "true" }}
      serviceAccountName: adp-reader
      {{- end }}
      initContainers:
        {{- include "dependencyChecker.initContainer" . | nindent 8 }}
      containers:
        - env:
            - name: MKL_NUM_THREADS
              value: "2"
            - name: LOG_SPACES
              value: "2097152"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DEPLOYMENT_ENVIRONMENT
              value: TKE
            - name: NAME_SPACE
              value: default
            - name: ENV
              value: tcs
            - name: SERVER_LOG_LEVEL
              value: info
            - name: TZ
              value: Asia/Shanghai
          image: {{(index .Values.images "adp-plugin-code-interpret").url}}
          imagePullPolicy: Always
          name: adp-plugin-code-interpret
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 20
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 8000
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 2
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 8000
            timeoutSeconds: 2
          #command: ["sh","-c", "crond start; touch /var/log/log.txt && tail -f /var/log/log.txt"]
          #command: ["sh","/usr/local/app/start.sh"]
          {{- if eq .Values.global.clusterSize "minimal" }}
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          {{- else if eq .Values.global.clusterSize "standard" }}
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          {{- else }}
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          {{- end }}
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /app/logs
              name: logdata
              subPathExpr: $(POD_NAME)
            - mountPath: /app/conf/trpc_go.yaml
              subPath: trpc_go.yaml
              name: config
            - mountPath: /app/conf/main.yaml
              subPath: main.yaml
              name: config
            - mountPath: /app/conf/placeholder.yaml
              subPath: placeholder.yaml
              name: config
            - mountPath: /app/conf/kube.yaml
              subPath: kube.yaml
              name: config
            - mountPath: /app/conf/infrastructure.yaml
              name: infrastructure
              subPath: infrastructure.yaml
      restartPolicy: Always
      volumes:
        {{- include "dependencyChecker.volumes" . | nindent 8 }}
        - hostPath:
            path: /etc/localtime
          name: localtime
        - hostPath:
            path: /data/ti-platform/log/adp-plugin-code-interpret
            type: DirectoryOrCreate
          name: logdata
        - configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-plugin-code-interpret
          name: config
        - configMap:
            defaultMode: 420
            name: infrastructure
          name: infrastructure
