replicas: 1
tad:
  type: helm
  images:
    ai-gateway:
      url: "ccr.ccs.tencentyun.com/tke-market/ai-gateway:11_2604201604_feature_iaas_v3.2.4_71e2199b_private"
  instanceStrategy:
    level: region
  labels: {}
  namespace: algorithm
  product: llm-knowledge-engine
  registries:
    images: registry.tce.com
    packages: http://registry.tce.com:1181
  services: {}
imagePullSecretName: qcloudregistrykey
