{{- $clbScheme := default .Values.scheme .Values.clbScheme -}}
{{- if and .Values.ingress.enabled (eq $clbScheme "https") (not .Values.ingress.tlsSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-portal.fullname" . }}-clb-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  qcloud_cert_id: {{ .Values.clbCertId | quote }}
{{- end }}
