{{- if not .Values.LICENSE_INSTANCE_ID }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "agent-portal.fullname" . }}-license-instance
  labels:
    {{- include "agent-portal.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames: ["kube-system"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agent-portal.fullname" . }}-license-instance
  labels:
    {{- include "agent-portal.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agent-portal.fullname" . }}-license-instance
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
{{- end }}
