apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "agent-portal.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
