images:
  adp-platform-metrology:
    url: "{{ .Values.global.imageRegistry }}/tke-market/platform-metrology:34_2605071116_stable_v3.4.1.1_5baef15d_private	"
resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 2Gi
appName: adp-platform-metrology
replicas: 1
