images:
  adp-plugin-config:
    url: "{{ .Values.global.imageRegistry }}/tke-market/plugin-config:83_2607271740_stable_iaas_v4.0.3.0_0ccdfff7_private"
adppluginconfig:
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi
  dbtype: ''
replicas: 1
custom_plugin_share_enable: true
plugin_audit_enable: false
