images:
  adp-plugin-config:
    url: "{{ .Values.global.imageRegistry }}/tke-market/plugin-config:54_2606132011_stable_iaas_cos_edacb22b_private"
adppluginconfig:
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi
  dbtype: ''
replicas: 1
