images:
  adp-agent-config:
    url: "{{ .Values.global.imageRegistry }}/tke-market/agent-config-server:21_2607272104_stable_iaas_v4.0.3.0_7dae6f9c_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
