images:
  adp-agent-config:
    url: "{{ .Values.global.imageRegistry }}/tke-market/agent-config-server:7_2606132000_stable_iaas_cos_d2f8f784_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
