images:
  adp-kb-config:
    url: "{{ .Values.global.imageRegistry }}/tke-market/kb-config:66_2606151729_stable_iaas_cos_64289625_private"
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi
easy_graph_config:
  enabled: true
  url: ws://193.168.11.194:8190/gremlin
  user: easygraph
  password: MOCK_SECRET_KEY_VALUE
doc_to_index:
  runners: 5
  batch: 5
doc_release_max_limit: 100
excel_char_size_limit: 1000000
qa_extract_model_name: cs-normal
similar_question_model_name: cs-normal
sync_vector_add_batch_size: 30
sync_vector_deleted_batch_size: 100
replicas: 1
