tad:
  type: helm
  global:
    productType: lke
  namespace: ti-base
  registries:
    images: registry.tce.com
    packages: registry.tce.com:1181
  images:
    ti-perm-auth:
      url: ccr.ccs.tencentyun.com/tke-market/ti-auth-cust-trpc:feature_master_private_iaas_v3.2.4_d3cced6b_20260407
env: TEST
namespace: ti-base
imagePullSecretName: qcloudregistrykey
serviceName: ti-perm-auth
