images:
  ti-perm-auth:
    url: "{{ .Values.global.imageRegistry }}/tke-market/ti-auth-cust-trpc:stable_iaas_v4.0.3.0_b4b2bc0e_20260721"
env: TEST
namespace: ti-base
imagePullSecretName: qcloudregistrykey
serviceName: ti-perm-auth
replicas: 1
