images:
  ti-perm-auth:
    url: "{{ .Values.global.imageRegistry }}/tke-market/ti-auth-cust-trpc:master_private_e2f193a8_20260127"
env: TEST
namespace: ti-base
imagePullSecretName: qcloudregistrykey
serviceName: ti-perm-auth
replicas: 1
