images:
  adp-agent-exec-env:
    url: "{{ .Values.global.imageRegistry }}/tke-market/agent-exec-env:5_2608011502_stable_iaas_v4.0.3.0_56296a3b_private"
resources:
  limits:
    cpu: 4
    memory: 16Gi
  requests:
    cpu: 2
    memory: 8Gi
replicas: 1
