images:
  adp-agent-exec-env:
    url: "{{ .Values.global.imageRegistry }}/tke-market/agent-exec-env:7_2608051542_stable_iaas_v4.0.3.0_c722745d_private"
resources:
  limits:
    cpu: 4
    memory: 16Gi
  requests:
    cpu: 2
    memory: 8Gi
replicas: 1
