images:
  adp-platform-charger:
    url: "{{ .Values.global.imageRegistry }}/tke-market/finance-finance:2_2605191655_stable_v3.4.1.1_c33e8680_private"
resources:
  limits:
    cpu: "1"
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 2Gi
replicas: 1
