images:
  adp-platform-charger:
    url: "{{ .Values.global.imageRegistry }}/tke-market/finance-finance:4_2607011049_stable_iaas_v4.0.3.0_2eb58235_private"
resources:
  limits:
    cpu: "1"
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 2Gi
replicas: 1
