kind: ConfigMap
apiVersion: v1
metadata:
  name: infrastructure
  namespace: {{ .Release.Namespace }}
data:
  infrastructure.yaml: |
    infra:
        providers:
            chat.contentSecurity:
                provider: {{ .Values.global.contentSecurity.type }}
                bizType: {{ .Values.global.contentSecurity.bizType }}
        middlewares:
            cloudCredentials:
              - vendor: {{ .Values.global.components.s3.vendor }}
                usage: cos
                secretId: {{ .Values.global.components.s3.cos.secretId }}
                secretKey: {{ .Values.global.components.s3.cos.secretKey }}
            db:
              - vendor: {{ .Values.global.components.db.vendor }}
                providerType: {{ .Values.global.components.db.providerType }}
                host: {{ .Values.global.components.db.host }}
                port: {{ .Values.global.components.db.port }}
                user: {{ .Values.global.components.db.user }}
                password: {{ .Values.global.components.db.password }}
            redis:
              - vendor: {{ .Values.global.components.redis.vendor }}
                providerType: {{ .Values.global.components.redis.providerType }}
                cluster: {{ .Values.global.components.redis.cluster }}
                hosts:
                  - {{ index .Values.global.components.redis.hosts 0 }}
                port: {{ .Values.global.components.redis.port }}
                password: {{ .Values.global.components.redis.password }}
            es:
              - vendor: {{ .Values.global.components.es.vendor }}
                providerType: {{ .Values.global.components.es.providerType }}
                hosts:
                  - {{ index .Values.global.components.es.hosts 0 }}
                port: {{ .Values.global.components.es.port }}
                user: {{ .Values.global.components.es.user }}
                password: {{ .Values.global.components.es.password }}
            kafka:
              - vendor: {{ .Values.global.components.kafka.vendor }}
                providerType: {{ .Values.global.components.kafka.providerType }}
                hosts:
                  - {{ index .Values.global.components.kafka.hosts 0 }}
                port: {{ .Values.global.components.kafka.port }}
            clickhouse:
              - vendor: {{ .Values.global.components.clickhouse.vendor }}
                providerType: {{ .Values.global.components.clickhouse.providerType }}
                hosts:
                  - {{ index .Values.global.components.clickhouse.hosts 0 }}
                port: {{ .Values.global.components.clickhouse.port }}
                user: {{ .Values.global.components.clickhouse.user }}
                password: {{ .Values.global.components.clickhouse.password }}
                disabled: {{ dig "clickhouse" "disabled" false .Values.global.components }}
            s3:
                vendor: {{ .Values.global.components.s3.vendor }}
                providerType: {{ .Values.global.components.s3.providerType }}
                enableProxy: {{ .Values.global.components.s3.enableProxy }}
                cos:
                  secretId: {{ (.Values.global.components.s3.cos).secretId | default "" }}
                  secretKey: {{ (.Values.global.components.s3.cos).secretKey | default "" }}
                  appId: {{ (.Values.global.components.s3.cos).appId | default "" }}
                  bucket: {{ (.Values.global.components.s3.cos).bucket | default "" }}
                  region: {{ (.Values.global.components.s3.cos).region | default "" }}
                  domain: {{ (.Values.global.components.s3.cos).domain | default "" }}
                  subPath: {{ (.Values.global.components.s3.cos).subPath | default "" }}
                  expireTime: {{ (.Values.global.components.s3.cos).expireTime | default "" }}
                  credentialTime: {{ (.Values.global.components.s3.cos).credentialTime | default "" }}
                s3:
                  secretId: {{ (.Values.global.components.s3.s3).secretId | default "" }}
                  secretKey: {{ (.Values.global.components.s3.s3).secretKey | default "" }}
                  bucket: {{ (.Values.global.components.s3.s3).bucket | default "" }}
                  region: {{ (.Values.global.components.s3.s3).region | default "" }}
                  subPath: {{ (.Values.global.components.s3.s3).subPath | default "" }}
                  expireTime: {{ (.Values.global.components.s3.s3).expireTime | default "" }}
                  credentialTime: {{ (.Values.global.components.s3.s3).credentialTime | default "" }}
                minio:
                  secretId: {{ (.Values.global.components.s3.minio).secretId | default "" }}
                  secretKey: {{ (.Values.global.components.s3.minio).secretKey | default "" }}
                  bucket: {{ (.Values.global.components.s3.minio).bucket | default "" }}
                  host: {{ (.Values.global.components.s3.minio).host | default "" }}
    
            vdb:
              {{- range $i, $v := .Values.global.components.vdb }}
              - vendor: {{ $v.vendor }}
                providerType: {{ $v.providerType }}
                addr: {{ $v.addr }}
                account: {{ $v.account }}
                apiKey: {{ $v.apiKey }}
              {{- end }}
            contentSecurity:
              type: {{ .Values.global.contentSecurity.type }}
              disableContentCheck: {{ .Values.global.contentSecurity.disableContentCheck }}
              auditSwitch: {{ .Values.global.contentSecurity.auditSwitch }}
              disableImageCheck: {{ .Values.global.contentSecurity.disableImageCheck }}
              bizType: {{ .Values.global.contentSecurity.bizType }}
              region: {{ .Values.global.contentSecurity.region }}
              appId: {{ .Values.global.contentSecurity.appId }}
              uin: {{ .Values.global.contentSecurity.uin }}
              subUin: {{ .Values.global.contentSecurity.subUin }}
              secretId: {{ .Values.global.contentSecurity.secretId }}
              secretKey: {{ .Values.global.contentSecurity.secretKey }}
              callbackUrl: {{ .Values.global.contentSecurity.callbackUrl }}
