images:
  adp-plugin-exec:
    url: ccr.ccs.tencentyun.com/tke-market/plugin-exec:15_2605062222_stable_v3.4.1.1_481925e1_private
  adp-plugin-exec-sidecar:
    url: ccr.ccs.tencentyun.com/tke-market/webappchatbot:markmap-96aaeac-24
adppluginexec:
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi
  secret_id: ''
  secret_key: ''
  doc_parse_secret_id: MOCK_CAPI_SECRET_ID_VALUE
  doc_parse_secret_key: MOCK_CAPI_SECRET_KEY_VALUE
  multi_model_name: cs-normal-mllm-72B
  doc_model_name_llm: cs-normal-70b
  web_page_parse_model_name: cs-normal-70b
  le_xiang_knowledge:
    search_url: ''
    token_url: ''
sidecar:
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi
replicas: 1
