images:
  adp-plugin-code-interpret:
    url: "{{ .Values.global.imageRegistry }}/tke-market/code-interpreter-dispatcher:9_2607161559_stable_iaas_v4.0.3.0_52a39f11_private"
adp-plugin-code-interpret:
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi
replicas: 1
