images:
  adp-plugin-code-interpret:
    url: "{{ .Values.global.imageRegistry }}/tke-market/code-interpreter-dispatcher:7_2606132010_stable_iaas_cos_03ff7eac_private"
adp-plugin-code-interpret:
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi
replicas: 1
