apiVersion: v1
kind: Service
metadata:
  labels:
    app: adp-app-channel-leader
  name: adp-app-channel-leader
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: tcp-9300
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: adp-app-channel-leader
  sessionAffinity: None
  type: ClusterIP
