images:
  adp-markmap-service:
    url: "{{ .Values.global.imageRegistry }}/tke-market/webappchatbot:markmap-stable_iaas_v4.0.3.0-5e4e6a0-81"
replicas: 1
resources:
  limits:
    cpu: "4"
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 1Gi
