apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-apisix-view-clusterrolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-apisix-view-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-apisix-view-serviceaccount
  namespace: {{ .Release.Namespace }}
