kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-file-converter
  namespace: {{ .Release.Namespace }}
data:
  FileManagerServer.yaml: |
    #k: v     # 使用yaml做配置管理，可以写注释
    base:                                         # 基础配置
      is_manager_server: true
      reload_interval: 30s                        # 路由表重载间隔
      enable_kafka_queue: true
      quota_cfg:
         qps: 30
         mllm_conc_num : 30
         split_conc_num: 30
    cut_config:
       tmp_dir: /usr/local/trpc/data/tmp           # 临时文件目录
  config.json: |
    {
      "FC_MYSQL_USER": "{{ .Values.global.components.db.user }}",
      "FC_MYSQL_PASSWORD": "{{ .Values.global.components.db.password }}",
      "FC_MYSQL_HOST": "{{ .Values.global.components.db.host }}",
      "FC_MYSQL_PORT": "{{ .Values.global.components.db.port }}",
      "FC_LOG_KAFKA_ADDR": "{{"{{"}} index .Values.global.components.kafka.hosts 0 }}:{{ .Values.global.components.kafka.port }}",
      "FC_LOG_KAFKA_TOPIC": "topic_doc_convert_test",
      "FC_LOG_KAFKA_GROUP": "doc_convert",
      "STORAGE_TYPE": "{{ .Values.global.components.s3.providerType | default "minio" }}",
      "SECRET_ID": "{{ .Values.global.components.s3.cos.secretId }}",
      "SECRET_KEY": "{{ .Values.global.components.s3.cos.secretKey }}",
      "STS_ENDPOINT": "http://cos-internal.{{ .Values.global.components.s3.cos.region }}.tencentcos.cn",
      "END_POINT": "cos-internal.{{ .Values.global.components.s3.cos.region }}.tencentcos.cn",
      "REGION": "",
      "BUCKET": "qbot",
      "USE_HTTPS": false,
      "URL_EXPIRE_TIME": "168h",
      "FILE_EXPIRE_TIME": "4320h"
    }

  trpc_go.yaml: |
    global: #全局配置
        namespace: Production                        #环境类型，分正式Production和非正式Development两种类型
        env_name: formal                        #环境名称，非正式环境下多环境的名称
        admin_port: 18888                              #管理命令服务端口
        enable_set: Y                      #是否启用set
        full_set_name: llm.cs.2                     #set名
    server:                                            #服务端配置
      app: SmartAssistant                                 #业务的应用名
      server: FileManagerServer                           #进程服务名
      bin_path: /usr/local/trpc/bin/                   #二进制可执行文件和框架配置文件所在路径
      conf_path: /usr/local/trpc/conf/                 #业���配置文件所在路径
      data_path: /usr/local/trpc/data/                 #业务数据文件所在路径
      filter:                                          #针对所有service处理函数前后的拦截器列表
        - recovery                                     #拦截框架创建的业务处理协程panic
        - galileo
      admin:
        port: 18888                                    # admin 端口
        read_timeout: 3000                             #ms. 请求被接受到请求信息被完全读取的超时时间设置，防止慢客户端
        write_timeout: 60000                           #ms. 处理的超时时间
      service:                                         #业务服务提供的service，可以有多个
        - name: trpc.SmartAssistant.FileManagerServer.ManagerObj #service的路由名称，请将ReplaceMe改成自己的service名字，app server占位符不要改
          disable_request_timeout: true
          network: tcp #网络监听类型  tcp udp
          protocol: trpc #应用层协议 trpc http
          timeout: 10000 #请求最长处理时间 单位 毫秒 （腾讯 vdb 创建 collection 需要 6.5s，耗时设为 10s，避免超时）
          registry: polaris #服务启动时使用的服务注册方式
          port: 10001
    client:                                            #客户端调用的后端配置
      filter:                                          #针对所有后端调用函数前后的拦截器列表
        - galileo
      namespace: Production                          #针对所有后端的环境
      timeout: 3000                                    #针对所有后端的请求最长处理时间
      service:
        - name: trpc.fm.redis.lock
          target: ip://${INFRA_MIDDLEWARES_REDIS_0_HOSTS}:6379/1
          password: ${INFRA_MIDDLEWARES_REDIS_0_PASSWORD}
          timeout: 3000
        - name: trpc.fm.redis.queue
          target: ip://${INFRA_MIDDLEWARES_REDIS_0_HOSTS}:6379/1
          password: ${INFRA_MIDDLEWARES_REDIS_0_PASSWORD}
          timeout: 3000
        - name: trpc.fm.mysql.task        # tdsql 数据库
          namespace: Production
          target: dsn://${INFRA_MIDDLEWARES_DB_0_USER}:${INFRA_MIDDLEWARES_DB_0_PASSWORD}@tcp(${INFRA_MIDDLEWARES_DB_0_HOST}:${INFRA_MIDDLEWARES_DB_0_PORT})/parsing_engine_v3?timeout=10s&parseTime=true&loc=Local
        - name: trpc.kafka.addmaintask.service
          target: ${INFRA_MIDDLEWARES_KAFKA_0_HOSTS}:${INFRA_MIDDLEWARES_KAFKA_0_PORT}?topic=maintasknew
        - name: qbot.qbot.admin.Api      # 标品回调
          callee: qbot.qbot.admin.Api
          protocol: trpc
          network: tcp
          timeout: 3000
          namespace: Production
          disable_servicerouter: true
          target: ip://adp-app-admin-proxy.{{ .Release.Namespace }}.svc.cluster.local:9092
    plugins:                                           #插件配置
      selector:
        polaris:
          protocol: grpc #北极星交互协议支持 http，grpc，trpc
          discovery:
            refresh_interval: 10000                    #北极星服务发现刷新间隔，123默认10000
      log:                                            #日志配置
        default:                                      #默认日志的配置，可支持多输出
          - writer: galileo                           # 将普通日志也上报到伽利略，就不用服务再配置cls日志收集了
            level: debug                              # 上报伽利略的日志等级
          - writer: file                              #本地文件日志
            level: debug                              #本地文件滚动日志的级别
            caller_skip: 4
            writer_config:
              filename: /usr/local/trpc/log/trpc.log                      #本地文件滚动日志存放的路径
              max_size: 50                              #本地文件滚动日志的大小 单位 MB
              max_backups: 10                           #最大日志文件数
              max_age: 7                                #最大日志保留天数
              compress:  false                          #日志文件是否压缩
        cls-log-trace:                                      #默认日志的配置，可支持多输出
          - writer: file                              #本地文件日志
            level: info                               #本地文件滚动日志的级别
            caller_skip: 4
            writer_config:
              filename: /usr/local/trpc/log/trace.log                      #本地文件滚动日志存放的路径
              max_size: 100                             #本地文件滚动日志的大小 单位 MB
              max_backups: 10                           #最大日志文件数
              max_age: 7                                #最大日志保留天数
              compress:  false                          #日志文件是否压缩
      telemetry:
        opentelemetry:
          addr: {{ ((.Values.global.observability).apm).otlp | default "" }}
          tenant_id: adp
          sampler:
            fraction: 1
          traces:
            disable_trace_body: false
          metrics:
            {{- if ((.Values.global.observability).apm).registry }}
            registry_endpoints: ["{{ .Values.global.observability.apm.registry}}"]
            {{- end }}
          logs:
            enabled: true
            level: "debug"
            trace_log_mode: "disable"
          {{- if ((.Values.global.observability).apm).attributes }}
          attributes:
            {{- range $key, $value := .Values.global.observability.apm.attributes }}
          - key: {{ $key }}
            value: {{ $value }}
            {{- end }}
          {{- end }}
