apiVersion: v1
kind: Service
metadata:
  labels:
    app: adp-file-converter
  name: adp-file-converter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-30007-30007
      port: 30007
      protocol: TCP
      targetPort: 30007
    - name: adp-file-converter-10001
      port: 10001
      protocol: TCP
      targetPort: 10001
  selector:
    app: adp-file-converter
  type: ClusterIP
