apiVersion: v1
kind: Service
metadata:
  name: adp-file-converter
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ports:
    - name: tcp-30007-30007
      port: 30007
      protocol: TCP
      targetPort: 30007
  selector:
    app: adp-file-converter
  type: ClusterIP
