images:
  adp-widget-config:
    url: "{{ .Values.global.imageRegistry }}/tke-market/widget-config:4_2607281133_stable_iaas_v4.0.3.0_a7b4f848_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
