images:
  adp-workflow-exec:
    url: "{{ .Values.global.imageRegistry }}/tke-market/workflow-exec:12_2607171547_stable_iaas_v4.0.3.0_f7eda322_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
