images:
  adp-workflow-exec:
    url: "{{ .Values.global.imageRegistry }}/tke-market/workflow-exec:10_2606132016_stable_iaas_cos_89fe386b_private"
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
replicas: 1
