images:
  entity-extractor-server:
    url: "{{ .Values.global.imageRegistry }}/tke-market/smartassistant.entityextractorserver:default-b-21-f_2.0.0.60_20260723141945_Tag_EntityExtractorServer_20250708_01_iaas"
replicas: 1
