images:
  entity-extractor-server:
    url: ccr.ccs.tencentyun.com/tke-market/smartassistant.entityextractorserver:default-b-20-f_2.0.0.59_20260503181436_Tag_EntityExtractorServer_20250708_01_iaas
replicas: 1
