apiVersion: v1
kind: Service
metadata:
  name: adp-access-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: adp-access-manager
spec:
  ports:
    - name: trpc
      port: 10001
      protocol: TCP
      targetPort: 10001
  selector:
    app: adp-access-manager
  sessionAffinity: None
  type: ClusterIP
