images:
  lke-bot-admin-config-server:
    url: "{{ .Values.global.imageRegistry }}/tke-market/bot-admin-config-server:25_2607171556_stable_iaas_v4.0.3.0_56418c0a_private"
experience_center_uin: '999999999'
replicas: 1
